function analyzeLongformText(text) {
  const words = String(text).match(/[A-Za-z0-9]+(?:'[A-Za-z0-9]+)*/g) || [];
  return Object.freeze({
    characters: [...text].length,
    wordCount: words.length,
    sentenceCount: (text.match(/[.!?](?=\s|$)/g) || []).length,
  });
}

function section(seriesId, index, title, text) {
  return Object.freeze({
    id: `longform-${seriesId}-${String(index + 1).padStart(2, "0")}`,
    title,
    category: "stories",
    difficulty: "natural",
    tags: Object.freeze(["narrative", "longform", "connected-prose"]),
    text,
    ...analyzeLongformText(text),
  });
}

function story(id, title, entries) {
  return Object.freeze({
    id,
    title,
    sections: Object.freeze(entries.map(([sectionTitle, text], index) => section(id, index, sectionTitle, text))),
  });
}

export const FLOW_LONGFORM_SERIES = Object.freeze([
  story("station", "A Different Route", [
    ["The Closed Platform", "Mara reached the small station before sunrise with a backpack, a paper map, and enough time for coffee. The departure board was dark, and a red notice covered the ticket machine. Overnight rain had damaged the track beyond the river, so every train was suspended until noon. She could return home, wait for hours, or follow an old bus route shown on the map. The bus stop stood two streets away beside a bakery that was just opening. Mara folded the map, tightened her coat, and decided that a delayed journey did not have to become a wasted morning."],
    ["The Old Bus Route", "The bus arrived almost empty and moved slowly through villages that Mara had only seen from train windows. Without the usual speed, she noticed orchards behind stone walls, narrow roads climbing into fog, and school lights appearing one by one. The driver stopped at every small square, even when nobody was waiting. After forty minutes, the road ahead was blocked by a fallen branch. The driver turned into a side street and explained the detour with a hand drawn route on his schedule. Mara realized that the unexpected trip was carrying her closer to the river than the train would have."],
    ["Across the River", "At the final stop, Mara still had six kilometers to travel. A walking path followed the river toward the town she needed to reach, and the rain had already weakened to a fine mist. She started along the path, passing wet fields and a row of old warehouses. Near a footbridge, she found a small notebook on a bench. The first page contained a name and a local address, so she slipped it into an outer pocket and kept walking. By the time the town church appeared above the trees, the missed train felt less important than returning the notebook before she left."],
    ["A Door on Linden Street", "The address led Mara to a narrow house on Linden Street, only three blocks from her original destination. An elderly man opened the door and recognized the notebook immediately. He had been sketching birds by the river the previous afternoon and thought the book was lost for good. Several pages held careful drawings, dates, and notes from years of walks through the same valley. Mara stayed only a few minutes, but the man showed her a shortcut through the market square that saved nearly half an hour. The detour that had begun with a broken railway now placed her ahead of schedule."],
    ["The Return Journey", "That evening, the trains were running again. Mara sat by the window as the carriage followed the repaired line beside the river. The trip home was faster, quieter, and far more familiar than the morning journey. She recognized the footbridge, the warehouses, and a distant road where the old bus had turned away from the blockage. None of those places had meant anything to her before. She opened her paper map and marked the walking path in pencil. The day had not gone according to plan, but it had given the route a shape that a timetable never could."],
  ]),
  story("garden", "The Courtyard Garden", [
    ["An Empty Courtyard", "The courtyard behind the apartment building had been ignored for years. A broken bench leaned against one wall, weeds filled the planting beds, and rainwater collected in two cracked containers. On a Saturday morning, Daniel went outside with gloves and three empty bags. He planned to clear one small corner before lunch. Within twenty minutes, two neighbors joined him, then another arrived with a broom and a box of old tools. Nobody had organized the work, but the courtyard slowly changed as each person chose an obvious task. By noon, a clean strip of soil appeared along the sunny wall."],
    ["A Simple Plan", "The next weekend, the group met again with a clearer idea. They measured the beds, checked where sunlight stayed longest, and wrote a short list of plants that could survive with limited care. Instead of buying everything at once, they divided the courtyard into three areas and agreed to finish one before starting the next. Daniel repaired the bench while others loosened the soil and removed stones. A child from the second floor drew labels for herbs on small wooden cards. The plan was modest, but it made the work easier because everyone could see what finished actually looked like."],
    ["First Green Shoots", "For several weeks, the courtyard seemed almost unchanged. The soil was darker, the paths were cleaner, and the bench stood straight, but the new plants remained small. Then warm weather arrived. Mint spread beside the wall, beans climbed their supports, and the first lettuce leaves opened after a night of rain. People who had never joined the work began stopping for a minute on their way inside. Someone added a watering can near the door, and another neighbor brought two chairs. The garden was still unfinished, yet it had already become a place where people expected to meet."],
    ["The Dry Week", "In July, a week of strong heat tested the new garden. The shallow containers dried first, and several leaves began to curl by midday. The group created a simple watering schedule on a sheet beside the entrance. Early risers covered the morning, while others checked the beds after work. They moved sensitive plants into partial shade and used cut grass to protect the soil. No single change solved the problem, but together the small adjustments kept most plants healthy. The difficult week also showed that the garden depended less on perfect conditions than on people noticing problems early and responding together."],
    ["A Shared Table", "By early autumn, the courtyard looked completely different. The old bench sat under climbing beans, herbs filled the narrow bed, and the cracked containers had been replaced with sturdy boxes. The group harvested more than they could use at once, so they placed a long table near the entrance and shared a simple meal. Nothing on the table was impressive by itself, but nearly every dish contained something grown a few meters away. Daniel looked around at neighbors who had once passed each other without speaking. The garden had improved the courtyard, but its most important result was the habit of returning."],
  ]),
  story("observatory", "The Night Shift", [
    ["Night Shift", "Leah began her first night shift at the university observatory just after sunset. Her task was routine: check the weather station, open the dome, align the telescope, and record a standard set of calibration images. The senior researcher would arrive later for the main observation. Outside, the sky was clear enough to see the first stars, and the wind stayed below the safety limit. Leah worked through the checklist slowly because she did not want to miss a small step. When the telescope finally moved to its starting position, every indicator on the control screen showed green."],
    ["A Faint Signal", "During calibration, one image contained a faint point of light near the edge of the frame. Leah assumed it was noise and repeated the exposure. The point appeared again, slightly farther to the east. She checked the star catalog, compared the previous image, and confirmed that the object was moving. It was too slow for an aircraft and too steady for a camera error. Leah saved the raw files before changing any settings. Then she searched recent observation notices to see whether another team had reported an object in the same region. Nothing matched the position on her screen."],
    ["Checking the Evidence", "The senior researcher arrived twenty minutes later and reviewed Leah's files without changing them. Together they repeated the observation with a shorter exposure and a different filter. The moving point remained visible. They measured its position, noted the exact time of each image, and compared the motion with known satellites and minor planets. One possible match appeared, but its predicted path was several minutes away from the measured track. Rather than announce anything, they prepared a compact report and sent the coordinates to another observatory that still had darkness. Confirmation from a second instrument would matter more than excitement in the room."],
    ["A Second Observatory", "An hour later, a message arrived from a telescope hundreds of kilometers west. The second team had found the same moving point within a few seconds of the predicted position. Their measurements reduced the uncertainty enough to connect the object with a faint asteroid that had been observed only once years earlier. Leah's images were not a dramatic discovery of something entirely new, but they recovered an object whose orbit had been poorly known. The distinction mattered. Good science depended on describing the evidence accurately, even when a more exciting story would be easier to tell."],
    ["Morning Light", "Near dawn, Leah closed the dome and started the final backup. The sky outside had turned pale blue, and the stars disappeared one by one from the monitor. She had expected the shift to teach her how to operate the telescope. Instead, the most useful lesson had been about patience. A faint point on one image had become meaningful only because she repeated the exposure, protected the raw data, checked alternatives, and waited for independent confirmation. Before leaving, she added one sentence to her notes: unusual results deserve attention, but they also deserve careful verification."],
  ]),
  story("harbor", "The Coastal Trail", [
    ["Fog at the Harbor", "Evan arrived at the harbor before seven with a camera, a small lunch, and a plan to walk the entire coastal trail. Thick fog covered the water, hiding the opposite pier and muting the sound of boats. The trail remained open, but the information board warned that visibility could change quickly near the cliffs. Evan considered postponing the walk. Instead, he shortened the route on his map and chose a section that stayed close to the village for the first hour. The decision felt less adventurous, but it left room to turn back without wasting the whole day."],
    ["The Higher Path", "As Evan climbed above the harbor, the fog began to thin. The lower trail stayed wet from overnight rain, so he followed a higher path through grass and low shrubs. From there, the coastline appeared in brief openings between clouds. He stopped often, not because the climb was difficult, but because the scene changed every few minutes. A lighthouse emerged, vanished, and appeared again farther along the ridge. Evan noticed that the slower route gave him better photographs than the direct trail would have. The weather had reduced his distance, yet it had improved his attention."],
    ["A Change in the Wind", "Near midday, the wind shifted toward the sea and pushed the remaining fog away from the cliffs. The wider view revealed dark clouds building beyond the lighthouse. Evan checked the forecast he had saved before leaving; rain was expected later, but the new clouds were arriving early. He reached a marked junction where the coastal trail continued for another eight kilometers while a farm road returned directly to the village. The longer path was tempting now that visibility was excellent. He chose the farm road anyway, trusting the change in weather more than the original plan."],
    ["Rain on the Farm Road", "The first heavy drops arrived fifteen minutes after Evan left the ridge. By the time he reached the stone farm buildings, rain covered the valley and the cliffs had disappeared again. He waited under a broad roof while the storm passed. A farmer pointed out a public footpath that connected the road to the harbor without returning to the exposed hillside. When the rain weakened, Evan followed it through fields and a line of trees. His shoes were soaked, but he reached the village safely and still had enough daylight to walk along the sheltered waterfront."],
    ["The Shorter Route", "Evan ended the day with fewer kilometers than he had planned and more photographs than expected. Some showed the harbor hidden in fog, others caught the lighthouse between clouds, and the final images reflected rain on the quiet waterfront. Looking through them, he saw a record of repeated decisions rather than a single completed route. Each change had made the walk shorter, but none had made it worse. The trail reminded him that a plan can guide a day without controlling it. Sometimes the useful skill is not holding the original course, but knowing when to choose another one."],
  ]),
  story("archive", "The Basement Archive", [
    ["The Basement Archive", "Nina volunteered to help a local history group organize boxes stored beneath the town library. Most contained ordinary records: meeting notes, event programs, old maps, and photographs with names written on the back. Her first job was not to interpret anything. She had to number each box, record its condition, and create a simple inventory. The work felt slow, but it prevented interesting items from becoming separated from their context. Near the end of the first afternoon, Nina opened a folder of photographs showing the same riverside building across several decades."],
    ["A Building That Changed", "The earliest photograph showed a narrow brick workshop beside the river. Later images showed larger windows, a new roof, and eventually a sign for a community hall. Nina found no single document explaining the changes, so she searched the inventory for the street name. Several meeting records mentioned repairs after floods, while an old planning map showed a proposed road that was never built. Piece by piece, the building's history became clearer. The photographs had first looked like a simple sequence, but the surrounding records showed how weather, money, and local decisions had shaped each change."],
    ["Missing Years", "A gap remained between two sets of photographs. For almost fifteen years, the archive contained no images of the building and very few records from the neighborhood. Nina resisted the temptation to fill the gap with a neat explanation. Instead, she marked the missing period in the catalog and asked the group whether other collections might help. One volunteer remembered that a retired newspaper photographer had donated negatives to a museum in the next town. The museum's online index listed the same street several times. A missing part of the story had become a research question rather than an excuse to guess."],
    ["The Contact Sheet", "The museum sent digital copies of a contact sheet a week later. Small frames showed the riverside building during a winter flood, then during repairs the following spring. One image included a temporary sign identifying the workshop as an emergency supply point. That detail connected several vague references in the meeting notes. Nina added the source information to the archive record and linked the new images to the existing folder. The discovery was satisfying, but the method mattered more: the answer came from preserving uncertainty, searching another collection, and documenting where the new evidence originated."],
    ["An Organized Story", "When the project ended, the history group prepared a small display about the riverside building. Visitors saw photographs, map details, and short excerpts from public records arranged by date. Nina noticed that the final display looked simple, even though building it had required weeks of careful cataloging. The simplicity was possible because the evidence remained organized behind the scenes. Every image had a source, every claim could be checked, and the missing years were explained honestly. The archive had not produced a perfect story. It had produced a reliable one, which was far more useful."],
  ]),
]);

export const FLOW_LONGFORM_PASSAGES = Object.freeze(
  FLOW_LONGFORM_SERIES.flatMap(({ sections }) => sections),
);
