import assert from "node:assert/strict";
import test from "node:test";
import { PRACTICE_DATABASE_VERSION,PRACTICE_RECORD_VERSIONS } from "../js/practiceLab/practiceConstants.js";
import { PRACTICE_READ_AHEAD_DURATIONS_MS,PRACTICE_READ_AHEAD_MASTER_SCHEDULE,PRACTICE_READ_AHEAD_VERSION,PRACTICE_READ_AHEAD_POLICY_VERSION,PRACTICE_READ_AHEAD_VISIBILITY_VERSION,PRACTICE_READ_AHEAD_SCHEDULE_VERSION,PRACTICE_READ_AHEAD_ANALYSIS_VERSION,PRACTICE_READ_AHEAD_RESULT_VERSION } from "../js/practiceLab/practiceReadAheadConstants.js";
import { getPracticeReadAheadProtocol } from "../js/practiceLab/practiceReadAheadPolicy.js";
import { buildPracticeReadAheadSchedule } from "../js/practiceLab/practiceReadAheadSchedule.js";
import { buildPracticeReadAheadLexicalIndex,getPracticeReadAheadVisibilityEnvelope,isPracticeReadAheadIndexVisible } from "../js/practiceLab/practiceReadAheadVisibility.js";
import { createPracticeReadAheadPlan,validatePracticeReadAheadPlan } from "../js/practiceLab/practiceReadAheadPlan.js";
import { analyzePracticeReadAhead,classifyPracticeReadAheadPattern } from "../js/practiceLab/practiceReadAheadAnalysis.js";

test("PL34 keeps DB10 and freezes v1 envelopes",()=>{assert.equal(PRACTICE_DATABASE_VERSION,10);assert.equal(PRACTICE_RECORD_VERSIONS.sessionSummary,13);for(const v of [PRACTICE_READ_AHEAD_VERSION,PRACTICE_READ_AHEAD_POLICY_VERSION,PRACTICE_READ_AHEAD_VISIBILITY_VERSION,PRACTICE_READ_AHEAD_SCHEDULE_VERSION,PRACTICE_READ_AHEAD_ANALYSIS_VERSION,PRACTICE_READ_AHEAD_RESULT_VERSION])assert.equal(v,1);});
test("PL34 protocols are exact",()=>{assert.deepEqual(PRACTICE_READ_AHEAD_DURATIONS_MS,[180000,360000,600000]);assert.deepEqual([180000,360000,600000].map(d=>{const p=getPracticeReadAheadProtocol(d);return[p.baselineMs,p.constrainedBlockCount,p.constrainedBlockMs,p.integrationMs]}),[[30000,6,20000,30000],[30000,12,25000,30000],[30000,18,30000,30000]]);});
test("PL34 schedules are balanced deterministic and never adjacent-identical",()=>{assert.deepEqual(PRACTICE_READ_AHEAD_MASTER_SCHEDULE,[1,2,4,2,1,4,2,4,1,4,2,1,4,1,2,1,4,2]);for(const duration of PRACTICE_READ_AHEAD_DURATIONS_MS){const a=buildPracticeReadAheadSchedule({sessionId:"practice-session_pl34-schedule-12345678",durationMs:duration});const b=buildPracticeReadAheadSchedule({sessionId:"practice-session_pl34-schedule-12345678",durationMs:duration});assert.deepEqual(a,b);for(let i=1;i<a.spans.length;i++)assert.notEqual(a.spans[i],a.spans[i-1]);const counts=new Map([1,2,4].map(n=>[n,a.spans.filter(x=>x===n).length]));assert.equal(counts.get(1),counts.get(2));assert.equal(counts.get(2),counts.get(4));}});
test("PL34 visibility shows active word plus exact future lexical words and preserves current boundary",()=>{const text='“one,” two three four five';const units=[{type:'word',startIndex:1,endIndex:4},{type:'word',startIndex:7,endIndex:10},{type:'word',startIndex:11,endIndex:16},{type:'word',startIndex:17,endIndex:21},{type:'word',startIndex:22,endIndex:26}];const index=buildPracticeReadAheadLexicalIndex({units,textLength:text.length});const one=getPracticeReadAheadVisibilityEnvelope({index,expectedIndex:1,visibleFutureWords:1});assert.equal(one.finalLexicalIndex,1);assert.equal(one.visibleEndIndex,11);assert.equal(isPracticeReadAheadIndexVisible(10,one),true);assert.equal(isPracticeReadAheadIndexVisible(11,one),false);const boundary=getPracticeReadAheadVisibilityEnvelope({index,expectedIndex:5,visibleFutureWords:1});assert.equal(boundary.activeLexicalIndex,1);assert.equal(isPracticeReadAheadIndexVisible(5,boundary),true);const back=getPracticeReadAheadVisibilityEnvelope({index,expectedIndex:1,visibleFutureWords:1});assert.equal(back.activeLexicalIndex,0);});
test("PL34 plan hash binds protocol form schedule and spans",()=>{const p=createPracticeReadAheadPlan({sessionId:"practice-session_pl34-plan-12345678",durationMs:360000,formSetId:"WS-READAHEAD-EN-1",formSetVersion:1,formId:"form-1",formHash:"sha256-fixture"});assert.equal(validatePracticeReadAheadPlan(p).valid,true);const bad=structuredClone(p);bad.constrainedBlocks[0].visibleFutureWords=4;bad.blocks[1].visibleFutureWords=4;assert.equal(validatePracticeReadAheadPlan(bad).valid,false);});
function block(id,kind,span,start,end,yBoost=0){const duration=end-start;const effective=60*Math.exp(yBoost);const correct=Math.round(effective*5*duration/60000);return{blockId:id,kind,visibleFutureWords:span,startMs:start,endMs:end,observedDurationMs:duration,acceptedForwardInsertions:correct,firstPassOpportunityCount:Math.max(correct,50),correctFirstPassAttempts:correct,eligibleTimingCount:20,disfluentTimingCount:2,correctionCostMs:100,visibilityInterrupted:false,contentExhausted:false,protocolCorrupt:false,difficultyStatus:'full',difficultyIndex:0,difficultyCoverage:1};}
test("PL34 analysis uses exact 4-vs-1 log response and descriptive thresholds",()=>{const s=buildPracticeReadAheadSchedule({sessionId:"practice-session_pl34-analysis-12345678",durationMs:180000});const blocks=s.blocks.map(b=>block(b.blockId,b.kind,b.visibleFutureWords,b.startMs,b.endMs,b.visibleFutureWords===4?Math.log(1.05):0));const r=analyzePracticeReadAhead({blockSnapshot:{blocks},durationMs:180000,scheduleVariant:s.variant});assert.ok(Math.abs(r.visibleSpanResponsePercent-5)<0.8);assert.equal(r.pattern,"more-preview-associated");assert.equal(classifyPracticeReadAheadPattern({visibleSpanResponsePercent:0,visibleSpanAccuracyDeltaPp:0}),"little-observed-difference");assert.equal(classifyPracticeReadAheadPattern({visibleSpanResponsePercent:-4,visibleSpanAccuracyDeltaPp:0}),"less-preview-associated");});
