import test from 'node:test';
import assert from 'node:assert/strict';
import { practiceDrillArtwork, practiceLibraryMatches, renderPracticeLabHome, disposePracticeLabPresentation } from '../js/practiceLab/practiceLabIdentity.js';
const card = { id:'weak-keys', title:'Weak Keys', description:'Practice difficult letters.', category:'precision', categoryLabel:'Precision', duration:'4–6 min',status:'available' };
function fixture() {return {title:'Practice Lab',helpAvailable:true,categories:[{id:'precision',title:'Precision',experiments:[card]}],analysis:[{route:'skill-map',title:'Skill Map',description:'Your local evidence.'}]};}
function rootFixture() {const listeners=new Map();return {innerHTML:'',querySelector:()=>null,addEventListener(name,fn){assert.ok(!listeners.has(name));listeners.set(name,fn);},removeEventListener(name,fn){assert.equal(listeners.get(name),fn);listeners.delete(name);},listeners};}
test('catalog uses actual available model, original route IDs, and honest status',()=>{const root=rootFixture();renderPracticeLabHome(root,fixture());assert.equal((root.innerHTML.match(/data-lab-drill=/g)??[]).length,1);assert.ok(root.innerHTML.includes('1 experiments · Choose freely'));assert.ok(root.innerHTML.includes('data-experiment-id="weak-keys"'));assert.ok(root.innerHTML.includes('Ready to train'));assert.ok(root.innerHTML.includes('Assessment is optional.'));assert.ok(!root.innerHTML.includes('No skill profile yet'));assert.ok(!root.innerHTML.includes('100 WPM'));disposePracticeLabPresentation(root);});
test('search matches all terms case-insensitively and combines with skill category',()=>{assert.ok(practiceLibraryMatches(card,'  WEAK  letters ','precision'));assert.ok(practiceLibraryMatches(card,'','all'));assert.ok(!practiceLibraryMatches(card,'weak','speed'));assert.ok(!practiceLibraryMatches(card,'nonexistent','all'));assert.ok(!practiceLibraryMatches(card,'weak bananas','all'));});
test('all model strings and attribute content are escaped',()=>{const view=fixture();view.categories[0].title='<img src=x onerror=alert(1)>';view.categories[0].experiments=[{...card,id:'unknown',title:'<img src=x onerror=alert(1)>',description:'</p><script>bad()</script>',categoryLabel:'" onclick="bad()'}];view.analysis=[{route:'skill-map',title:'<svg onload="bad()">',description:'<script>bad()</script>'}];const root=rootFixture();renderPracticeLabHome(root,view);assert.ok(!root.innerHTML.includes('<img'));assert.ok(!root.innerHTML.includes('<script>'));assert.ok(root.innerHTML.includes('&lt;img'));assert.ok(root.innerHTML.includes('&quot; onclick='));assert.ok(!root.innerHTML.includes('<svg onload='));disposePracticeLabPresentation(root);});
test('artwork is a fixed allowlist and never incorporates untrusted IDs',()=>{assert.equal(practiceDrillArtwork('<script>bad()</script>'),practiceDrillArtwork('full-assessment'));assert.ok(practiceDrillArtwork('weak-keys').includes('aria-hidden="true"'));assert.ok(!practiceDrillArtwork('weak-keys').includes('<image'));assert.equal(practiceDrillArtwork('toString'),practiceDrillArtwork('full-assessment'));assert.notEqual(practiceDrillArtwork('weak-keys'),practiceDrillArtwork('pace-ladder'));});
test('home has native controls, a labeled search, non-color filter state, and live count',()=>{const root=rootFixture();renderPracticeLabHome(root,fixture());for(const text of ['aria-label="Practice Lab navigation"','aria-current="page"','type="search"','Find a drill','aria-pressed="true"','aria-live="polite"','No matching drills','data-lab-action="reset"'])assert.ok(root.innerHTML.includes(text),text);disposePracticeLabPresentation(root);});
test('re-rendering keeps exactly one listener pair and unmount removes both',()=>{const root=rootFixture();renderPracticeLabHome(root,fixture());renderPracticeLabHome(root,fixture());assert.equal(root.listeners.size,2);disposePracticeLabPresentation(root);assert.equal(root.listeners.size,0);disposePracticeLabPresentation(root);renderPracticeLabHome(root,fixture());assert.equal(root.listeners.size,2);disposePracticeLabPresentation(root);});
test('optional assessment follows actionable drill groups instead of blocking them',()=>{const view=fixture();view.categories.unshift({id:'assessment',title:'Assessment',experiments:[{...card,id:'full-assessment',category:'assessment'}]});const root=rootFixture();renderPracticeLabHome(root,view);assert.ok(root.innerHTML.indexOf('data-lab-drill="weak-keys"')<root.innerHTML.indexOf('data-lab-drill="full-assessment"'));disposePracticeLabPresentation(root);});
