import { createPracticeSessionPulse } from "./practiceSessionPulse.js";
import { createPracticeIndexedDbStore } from "./practiceIndexedDbStore.js";
import { createPracticeManifestStore } from "./practiceManifestStore.js";
import { createPracticeRepository } from "./practiceRepository.js";
import { createPracticeSessionEngine } from "./practiceSessionEngine.js";
import { PRACTICE_CONSISTENCY_POLICY_V1 } from "./practiceConsistencyPolicy.js";

const INSERT_TYPES = new Set(["insertText", "insertCompositionText"]);
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
const finite = Number.isFinite;
const n = (value, digits = 1) => finite(value) ? Number(value).toFixed(digits).replace(/\.0$/, "") : "—";
const pp = (value) => finite(value) ? `${value >= 0 ? "+" : ""}${n(value)} pp` : "—";
const pct = (value) => finite(value) ? `${n(value)}%` : "—";
const normalizedInput = (type, value) => ({ type, value, source: "browser-input", monotonicTimestampMs: Math.max(0, globalThis.performance?.now?.() ?? Date.now()), wallTimestampUtc: new Date().toISOString(), modifiers: { ctrl: false, meta: false, alt: false, shift: false } });
const formatRemaining = (ms) => { const total = Math.max(0, Math.ceil(ms / 1000)); return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, "0")}`; };

function renderText(contentPlan, snapshot) {
  const chars = Array.from(contentPlan.text); const cursor = snapshot.cursorIndex ?? 0; const errors = new Set(snapshot.errorPositions ?? []); const start = Math.max(0, cursor - 140); const end = Math.min(chars.length, cursor + 520);
  return chars.slice(start, end).map((value, offset) => { const index = start + offset; const classes = ["practice-real-text-char"]; if (index < cursor) classes.push(errors.has(index) ? "is-error" : "is-typed"); if (index === cursor) classes.push("is-current"); return `<span class="${classes.join(" ")}">${value === " " ? "&nbsp;" : escapeHtml(value)}</span>`; }).join("");
}
function guideCopy(status, calibration) {
  if (calibration) return "Type naturally at a comfortable pace.";
  return ({ steady: "Steady", faster: "A little faster than your reference", slower: "A little slower than your reference", collecting: "Finding your current pace…", unavailable: "Steadiness guide unavailable for this session" })[status] ?? "Finding your current pace…";
}
function renderActive(root, session, snapshot, { announcement = "" } = {}) {
  const activeMs = snapshot.timing?.activeDurationMs ?? 0; const remaining = Math.max(0, session.plan.durationMs - activeMs); const consistency = session.experiment?.id === "consistency-trainer";
  const guide = consistency ? session.experiment.consistencyGuide?.getSnapshot(activeMs) : null;
  const heading = consistency ? "Consistency" : session.flow === "check" ? "Endurance Check" : "Endurance Practice";
  const sub = consistency ? guideCopy(guide?.status, guide?.calibration) : `${formatRemaining(remaining)} remaining`;
  root.innerHTML = `<section class="screen practice-lab-screen" data-practice-view="sustained-session" data-sustained-flow="${escapeHtml(session.flow)}"><div class="practice-lab-shell"><header class="practice-real-text-session-header"><div><div class="eyebrow">${heading}</div><h1>${escapeHtml(sub)}</h1><p>${consistency ? `${formatRemaining(remaining)} remaining` : "Type naturally. Live WPM and aggregate accuracy are hidden."}</p></div><button type="button" data-sustained-session-action="stop">STOP</button></header><div class="practice-weak-key-progress" role="progressbar" aria-label="Session time" aria-valuemin="0" aria-valuemax="${session.plan.durationMs}" aria-valuenow="${Math.min(session.plan.durationMs, Math.round(activeMs))}"><span style="width:${Math.min(100, activeMs / session.plan.durationMs * 100).toFixed(2)}%"></span></div>${consistency ? `<div class="practice-lab-notice" data-consistency-guide="${escapeHtml(guide?.status ?? "collecting")}">${escapeHtml(guideCopy(guide?.status, guide?.calibration))}</div><span class="sr-only" aria-live="polite">${escapeHtml(announcement)}</span>` : ""}<section class="practice-real-text-typing" aria-label="${heading} typing material">${renderText(session.contentPlan, snapshot)}</section><textarea data-sustained-input aria-label="${heading} typing input" inputmode="text" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" style="position:fixed;left:-10000px;top:0;width:1px;height:1px;opacity:0"></textarea></div></section>`;
}
function abilityInterval(estimate) { return finite(estimate?.interval95LowerWpm) && finite(estimate?.interval95UpperWpm) ? `${n(estimate.interval95LowerWpm)}–${n(estimate.interval95UpperWpm)} WPM` : "—"; }
function patternLabel(value) { return ({ steady: "Steady", variable: "Variable", "drifting-faster": "Drifting faster", "drifting-slower": "Drifting slower", mixed: "Mixed", borderline: "Borderline", stable: "Stable", "pace-decline": "Pace decline", "control-decline": "Control decline", "mixed-decline": "Mixed decline", rising: "Rising", uncertain: "Uncertain", insufficient: "Insufficient" })[value] ?? value ?? "—"; }
export function renderPracticeSustainedResult(root, session, finalResult, abilityState = null) {
  const result = finalResult?.summary?.trainingQuality ?? null; const consistency = session.experiment?.id === "consistency-trainer"; const check = session.flow === "check"; const ability = abilityState?.estimate ?? abilityState?.currentEstimate ?? null;
  if (consistency) {
    root.innerHTML = `<section class="screen practice-lab-screen" data-practice-view="consistency-result"><div class="practice-lab-shell"><main class="practice-lab-detail"><div class="eyebrow">Consistency Trainer result</div><h1>${patternLabel(result?.pace?.pattern)}</h1><section class="practice-lab-empty-state"><h2>Pace Stability</h2><dl class="practice-real-text-result-grid"><div><dt>Pace variation</dt><dd>${pct(result?.pace?.variationPercent)}</dd></div><div><dt>Pattern</dt><dd>${patternLabel(result?.pace?.pattern)}</dd></div></dl><p>Variation measures robust short-timescale movement around your own session pace trend.</p></section><section class="practice-lab-empty-state"><h2>Pace Drift</h2><dl class="practice-real-text-result-grid"><div><dt>Session drift</dt><dd>${pct(result?.pace?.driftPercent)}</dd></div><div><dt>Adjusted median pace</dt><dd>${n(result?.pace?.medianAdjustedGrossWpm)} WPM</dd></div></dl><p>Drift measures directional change; it is kept separate from variation.</p></section><section class="practice-lab-empty-state"><h2>Control Stability</h2><dl class="practice-real-text-result-grid"><div><dt>First-pass accuracy variation</dt><dd>${n(result?.control?.accuracyMADpp)} pp</dd></div><div><dt>Disfluency variation</dt><dd>${n(result?.control?.disfluencyMADpp)} pp</dd></div><div><dt>Correction-cost variation</dt><dd>${n(result?.control?.correctionCostMADpp)} pp</dd></div><div><dt>Control stability</dt><dd>${escapeHtml(result?.control?.stability ?? "—")}</dd></div></dl></section><div class="practice-lab-notice">Variation measures how much your pace moved around its own trend. Drift measures whether your pace gradually changed during the session. Consistency Trainer does not create a 0–100 consistency score.</div><button type="button" data-sustained-session-action="finish">BACK TO CONSISTENCY</button></main></div></section>`;
  } else {
    root.innerHTML = `<section class="screen practice-lab-screen" data-practice-view="endurance-result"><div class="practice-lab-shell"><main class="practice-lab-detail"><div class="eyebrow">${check ? "Endurance Check result" : "Endurance Practice result"}</div><h1>${patternLabel(result?.pattern)}</h1>${check ? `<section class="practice-lab-empty-state"><h2>Endurance Ability</h2><dl class="practice-real-text-result-grid"><div><dt>Current endurance ability</dt><dd>${n(ability?.estimateWpm)} WPM</dd></div><div><dt>95% model interval</dt><dd>${abilityInterval(ability)}</dd></div><div><dt>Confidence</dt><dd>${escapeHtml(ability?.confidenceLevel ?? abilityState?.confidenceLevel ?? "—")}</dd></div></dl><p>Endurance ability is based on the final three minutes of the standardized 10-minute Check after continuous prior typing.</p></section>` : `<section class="practice-lab-empty-state"><h2>Sustained Pace</h2><p>${n(result?.validWindowCount, 0)} structurally valid 30-second windows were available for descriptive analysis.</p></section>`}<section class="practice-lab-empty-state"><h2>Late vs Early</h2><dl class="practice-real-text-result-grid"><div><dt>Early adjusted effective pace</dt><dd>${n(result?.earlyAdjustedEffectiveWpm)} WPM</dd></div><div><dt>Late adjusted effective pace</dt><dd>${n(result?.lateAdjustedEffectiveWpm)} WPM</dd></div><div><dt>Pace retention</dt><dd>${pct(result?.paceRetentionPercent)}</dd></div><div><dt>Pattern</dt><dd>${patternLabel(result?.pattern)}</dd></div></dl></section><section class="practice-lab-empty-state"><h2>Control</h2><dl class="practice-real-text-result-grid"><div><dt>First-pass accuracy</dt><dd>${pp(result?.control?.accuracyDeltaPp)}</dd></div><div><dt>Disfluency</dt><dd>${pp(result?.control?.disfluencyDeltaPp)}</dd></div><div><dt>Correction cost</dt><dd>${pp(result?.control?.correctionCostDeltaPp)}</dd></div></dl></section><section class="practice-lab-empty-state"><h2>${check ? "Consistency" : "Pace Variation"}</h2><p>Pace variation: ${pct(result?.pace?.variationPercent)}. Directional trend: ${pct(result?.pace?.trendPercent)}.</p></section><div class="practice-lab-notice">Endurance compares sustained typing later in the session with an earlier settled period. It describes performance change, not the reason for that change.</div><button type="button" data-sustained-session-action="finish">BACK TO ENDURANCE</button></main></div></section>`;
  }
  root.querySelector?.("[data-sustained-session-action='finish']")?.focus?.({ preventScroll: true });
}

export async function mountPracticeSustainedSession({ root, session, runtime = null, onExit = () => {}, logger = null, dependencies = {} } = {}) {
  if (!root?.addEventListener || !session?.experiment || !session?.contentPlan || !session?.plan) throw new TypeError("Sustained session host requires prepared session");
  const dataStore = dependencies.dataStore ?? createPracticeIndexedDbStore(); const repository = dependencies.repository ?? createPracticeRepository({ dataStore, manifestStore: dependencies.manifestStore ?? createPracticeManifestStore() }); const initialized = dependencies.initialized ?? await repository.initializePracticeStorage();
  if (initialized.profile.profileId !== session.plan.profileId || initialized.context.contextId !== session.plan.contextId) throw Object.assign(new Error("Practice context changed after PL29 preparation"), { code: "PRACTICE_CONTEXT_MISMATCH" });
  const engine = (dependencies.engineFactory ?? createPracticeSessionEngine)({ repository, sessionId: session.plan.sessionId, profileId: initialized.profile.profileId, contextId: initialized.context.contextId, logger });
  let closed = false; let interrupted = false; let completing = false; let finalResult = null; let unsubscribe = null; let pulseLoop = null; let lastGuideStatus = null; let lastAnnouncementAt = -Infinity;
  const running = () => !closed && !interrupted && !completing && !finalResult;
  const focus = () => queueMicrotask(() => { if (running()) root.querySelector?.("[data-sustained-input]")?.focus?.({ preventScroll: true }); });
  async function cleanup(notify = true) { if (closed) return; closed = true; pulseLoop?.stop(); unsubscribe?.(); root.removeEventListener("beforeinput", beforeInput); root.removeEventListener("keydown", keyDown); root.removeEventListener("click", click); globalThis.document?.removeEventListener?.("visibilitychange", visibilityChange); try { await engine.destroy(); } catch {} try { dataStore.close?.(); } catch {} if (notify) onExit(finalResult); }
  async function interrupt(reason = "manual-stop") { if (!running()) return; interrupted = true; pulseLoop?.stop(); try { finalResult = await engine.abandon(reason); } catch {} await cleanup(true); }
  const beforeInput = (event) => { const capture = event.target?.closest?.("[data-sustained-input]"); if (!capture || !root.contains?.(capture) || !running()) return; event.preventDefault(); if (INSERT_TYPES.has(event.inputType) && typeof event.data === "string") for (const char of Array.from(event.data.normalize("NFC"))) engine.handleInput(normalizedInput(char === " " ? "space" : "character", char)); else if (event.inputType === "deleteContentBackward") engine.handleInput(normalizedInput("backspace", "")); else if (event.inputType === "deleteWordBackward") engine.handleInput(normalizedInput("word-delete", "")); capture.value = ""; };
  const keyDown = (event) => { if ((event.ctrlKey || event.metaKey) && ["v", "x"].includes(String(event.key).toLowerCase())) event.preventDefault(); if (event.key === "Escape") { event.preventDefault(); void interrupt("manual-stop"); } };
  const click = (event) => { const button = event.target?.closest?.("[data-sustained-session-action]"); if (!button || !root.contains?.(button)) return; if (button.dataset.sustainedSessionAction === "stop") void interrupt("manual-stop"); else if (button.dataset.sustainedSessionAction === "finish") void cleanup(true); };
  const visibilityChange = () => { if (globalThis.document?.visibilityState === "hidden" && running()) void interrupt("visibility-hidden"); };
  function currentAnnouncement(snapshot) { if (session.experiment?.id !== "consistency-trainer") return ""; const activeMs = snapshot.timing?.activeDurationMs ?? 0; const guide = session.experiment.consistencyGuide?.getSnapshot(activeMs); const status = guide?.status ?? "collecting"; if (!["slower", "steady", "faster"].includes(status)) { lastGuideStatus = status; return ""; } if (status !== lastGuideStatus && activeMs - lastAnnouncementAt >= PRACTICE_CONSISTENCY_POLICY_V1.guideAnnouncementCooldownMs) { lastGuideStatus = status; lastAnnouncementAt = activeMs; return guideCopy(status, false); } lastGuideStatus = status; return ""; }
  async function pulse() { if (!running()) return; const tick = await engine.tick(); if (tick?.completed || !running()) return; const snapshot = engine.getSnapshot(); renderActive(root, session, snapshot, { announcement: currentAnnouncement(snapshot) }); focus(); }
  try {
    await engine.prepare({ experiment: session.experiment, configuration: session.configuration, contentPlan: session.contentPlan });
    unsubscribe = engine.subscribe((snapshot, event) => { if (!running() && event !== "completed") return; if (event === "completed") { completing = true; pulseLoop?.stop(); void engine.complete().then(async (result) => { if (closed || interrupted) return; finalResult = result; completing = false; const abilityState = session.flow === "check" ? await runtime?.getEnduranceAbilityState?.().catch(() => null) : null; renderPracticeSustainedResult(root, session, result, abilityState); }).catch((error) => { completing = false; logger?.warn?.("PL29 completion retrieval failed", error); void interrupt("measurement-corruption"); }); return; } if (snapshot.lifecycleState === "active") { renderActive(root, session, snapshot, { announcement: currentAnnouncement(snapshot) }); focus(); } });
    root.addEventListener("beforeinput", beforeInput); root.addEventListener("keydown", keyDown); root.addEventListener("click", click); globalThis.document?.addEventListener?.("visibilitychange", visibilityChange);
    const snapshot = await engine.start(); if (running()) { renderActive(root, session, snapshot); focus(); }
    pulseLoop = createPracticeSessionPulse({ ...dependencies.pulseTimers, intervalMs: 250, isActive: running, run: pulse, onError: async (error) => { logger?.warn?.("PL29 session timer failed", error); await interrupt("measurement-corruption"); } }); pulseLoop.start(); visibilityChange();
  } catch (error) { await cleanup(false); throw error; }
  return Object.freeze({ getSnapshot: () => engine.getSnapshot(), stop: () => interrupt("manual-stop"), interrupt, exit: cleanup });
}
