import { renderPracticeLabV25 } from "./practiceLabRendererV25.js";

const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[c]);
export function renderPracticePaceLadderDetail(root, view, { focusSelector = null } = {}) {
  const needsAnchor = view.availability?.mode === "user-selected-anchor-required";
  const measured = view.availability?.mode === "measured-anchor";
  const validManual = Number.isFinite(Number(view.userSelectedWpm)) && Number(view.userSelectedWpm) >= 5 && Number(view.userSelectedWpm) <= 400;
  const canStart = view.status === "ready" && !view.starting && (!needsAnchor || validManual);
  root.innerHTML = `<section class="screen practice-lab-screen" data-practice-view="pace-ladder-detail"><div class="practice-lab-shell"><header class="practice-lab-header"><button type="button" class="practice-lab-back" data-practice-action="back">← Back to Practice Lab</button><span class="practice-lab-status is-preview">DEVELOPER PREVIEW</span></header><main class="practice-lab-detail"><div class="eyebrow">Performance · diagnostic · ~3 min</div><h1>Pace Ladder</h1><p class="practice-lab-lead">Find the short-form pace where accuracy and control start to break down. This is target-free diagnostic text; PL14 owns the final Control Frontier inference.</p><section class="practice-lab-empty-state"><h2>Anchor</h2><p>${measured ? "A recent ordinary, target-free Real Text pace is available as the default anchor. You can explicitly override it below." : needsAnchor ? "No eligible ordinary-performance anchor is available. Choose a comfortable pace to run the diagnostic." : view.status === "loading" ? "Checking diagnostic prerequisites…" : "The diagnostic is currently unavailable."}</p><label for="pace-ladder-anchor"><strong>Comfortable pace (WPM)</strong></label><input id="pace-ladder-anchor" data-pace-anchor-input inputmode="numeric" type="number" min="5" max="400" step="1" value="${escapeHtml(view.userSelectedWpm)}" placeholder="Optional when a measured anchor exists" aria-describedby="pace-anchor-help"><p id="pace-anchor-help" class="practice-lab-muted">An explicit value always takes precedence. It is never inferred from targeted drills, Cold Transfer, Full Assessment, retention reviews, or burst observations.</p>${view.errorCode ? `<p role="alert">${escapeHtml(view.errorCode)}</p>` : ""}<button type="button" class="practice-lab-primary-action" data-practice-action="start-pace-ladder" ${canStart ? "" : "disabled"}>${view.starting ? "STARTING…" : "START PACE LADDER"}</button></section><section class="practice-lab-empty-state"><h2>Fixed protocol</h2><div style="overflow-x:auto;max-width:100%"><table><thead><tr><th>Stage</th><th>Time</th><th>Target</th></tr></thead><tbody><tr><td>Calibration</td><td>25 s</td><td>Comfortable anchor</td></tr><tr><td>1</td><td>25 s</td><td>85%</td></tr><tr><td>2</td><td>25 s</td><td>95%</td></tr><tr><td>3</td><td>25 s</td><td>105%</td></tr><tr><td>4</td><td>25 s</td><td>115%</td></tr><tr><td>5</td><td>25 s</td><td>125%</td></tr><tr><td>Validation</td><td>40 s</td><td>Anchor/control band</td></tr></tbody></table></div><p>Total active time: <strong>190 seconds</strong>. The ladder never asks for more than 125% of the anchor.</p></section><section class="practice-lab-empty-state"><h2>Evidence boundary</h2><p>This diagnostic can support pace-control evidence. It does not estimate true maximum speed, endurance, latent ability, fatigue capacity, or coaching readiness.</p><p>Interrupting the run stops it immediately and prevents a PL14 frontier update.</p></section></main></div></section>`;
  (root.querySelector?.(focusSelector) ?? root.querySelector?.("[data-practice-action='start-pace-ladder']") ?? root.querySelector?.("button"))?.focus?.({ preventScroll: true }); return true;
}
export function renderPracticeLabV26(root, view, options = {}) { if (view?.kind === "pace-ladder-detail") return renderPracticePaceLadderDetail(root, view, options); return renderPracticeLabV25(root, view, options); }
