import { createPracticeIndexedDbStore } from "./practiceIndexedDbStore.js";
import { createPracticeManifestStore } from "./practiceManifestStore.js";
import { createPracticeRepository } from "./practiceRepository.js";
import { createPracticeSessionEngine } from "./practiceSessionEngine.js";
import { assertPracticeAccuracyRecoverySessionContext } from "./practiceAccuracyRecoveryTrust.js";

const ACTION_SELECTOR = "[data-accuracy-recovery-session-action]";
const INSERT_TYPES = new Set(["insertText", "insertCompositionText"]);
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]);
const finite = Number.isFinite;
const number = (value, digits = 1) => finite(value) ? Number(value).toFixed(digits).replace(/\.0$/, "") : "—";
const percent = (value) => finite(value) ? `${number(value * 100, 1)}%` : "—";
const signed = (value, suffix = "") => finite(value) ? `${value >= 0 ? "+" : ""}${number(value, 1)}${suffix}` : "—";
const typeLabel = (type) => ({ key: "Key", bigram: "Bigram", trigram: "Trigram", word: "Word" })[type] ?? "Target";

function phaseForCursor(contentPlan, cursor) { const phases = contentPlan?.metadata?.accuracyRecovery?.phaseRanges ?? []; return phases.find((phase) => cursor >= phase.startIndex && cursor < phase.endIndex) ?? phases.find((phase) => phase.startIndex >= cursor) ?? phases.at(-1) ?? null; }
function highlighted(phase) { if (!phase || phase.cue === "none") return new Set(); const set = new Set(); for (const range of phase.targetRanges ?? []) for (let index = range.startIndex; index < range.endIndex; index += 1) set.add(index); return set; }
function renderText(contentPlan, snapshot, phase) { const graphemes = Array.from(contentPlan.text); const cursor = snapshot.cursorIndex ?? 0; const errors = new Set(snapshot.errorPositions ?? []); const target = highlighted(phase); const start = Math.max(phase?.startIndex ?? 0, Math.min(cursor, phase?.endIndex ?? cursor)); const end = Math.min(graphemes.length, phase?.endIndex ?? graphemes.length); return graphemes.slice(start, end).map((value, offset) => { const index = start + offset; const classes = ["practice-weak-key-char"]; if (index < cursor) classes.push(errors.has(index) ? "is-error" : "is-typed"); if (index === cursor) classes.push("is-current"); if (target.has(index)) classes.push("is-target-subtle"); return `<span class="${classes.join(" ")}">${value === " " ? "&nbsp;" : escapeHtml(value)}</span>`; }).join(""); }
function strip(contentPlan, active) { return `<ol class="practice-weak-key-phase-strip" aria-label="Accuracy & Recovery phases">${(contentPlan?.metadata?.accuracyRecovery?.phaseRanges ?? []).map((phase) => `<li data-phase-state="${phase.ordinal < (active?.ordinal ?? 1) ? "complete" : phase.id === active?.id ? "active" : "upcoming"}"><span>${phase.ordinal}</span><strong>${escapeHtml(phase.label)}</strong></li>`).join("")}</ol>`; }
function instruction(phase) { if (phase?.id === "baseline") return "Type naturally. No intervention feedback is shown in Baseline."; if (phase?.id === "control") return "Aim for clean first-pass typing at a comfortable normal pace."; if (phase?.id === "repair") return "Type normally. If an error happens, repair it precisely and return to your rhythm."; if (phase?.id === "mix") return "Apply the same control in mixed target-bearing and target-free material."; if (phase?.id === "check") return "Final same-session Check. Type naturally; intervention feedback is off."; return "Type the displayed text."; }

export function renderPracticeAccuracyRecoverySessionSnapshot(root, { contentPlan, snapshot, repairFeedback = null }) {
  const phase = phaseForCursor(contentPlan, snapshot.cursorIndex ?? 0); const target = contentPlan.metadata.accuracyRecovery.target; const total = snapshot.content?.expectedLength ?? Array.from(contentPlan.text).length; const progress = total ? Math.min(100, ((snapshot.cursorIndex ?? 0) / total) * 100) : 0; const paused = snapshot.lifecycleState === "paused";
  root.innerHTML = `<section class="screen practice-lab-screen practice-weak-key-session" data-practice-view="accuracy-recovery-session"><div class="practice-lab-shell"><header class="practice-weak-key-session-header"><div><div class="eyebrow">Accuracy & Recovery · ${typeLabel(target.entityType)}</div><h1>Practicing: ${escapeHtml(target.entityKey)}</h1></div><div class="practice-weak-key-session-actions"><button type="button" data-accuracy-recovery-session-action="${paused ? "resume" : "pause"}">${paused ? "RESUME" : "PAUSE"}</button><button type="button" data-accuracy-recovery-session-action="abandon">EXIT SESSION</button></div></header>${strip(contentPlan, phase)}<section class="practice-weak-key-phase-card" aria-live="polite"><div class="practice-lab-card-meta"><span>Phase ${phase?.ordinal ?? "—"} of 5 · ${escapeHtml(phase?.label ?? "")}</span><span>${phase?.opportunityQuota ?? "—"} target opportunities</span></div><p>${escapeHtml(instruction(phase))}</p></section><div class="practice-weak-key-progress"><span style="width:${progress.toFixed(2)}%"></span></div><div class="practice-weak-key-progress-label">${Math.round(progress)}% complete</div><section class="practice-weak-key-typing" data-session-paused="${paused ? "true" : "false"}">${renderText(contentPlan, snapshot, phase)}</section><div class="practice-lab-notice" data-repair-feedback aria-live="polite" ${repairFeedback ? "" : "hidden"}>${repairFeedback ? `<strong>${escapeHtml(repairFeedback.message)}</strong>` : ""}</div>${paused ? '<div class="practice-lab-notice" role="status"><strong>Paused.</strong></div>' : ""}<textarea data-accuracy-recovery-input aria-label="Accuracy & Recovery typing input" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" style="position:fixed;left:-10000px;top:0;width:1px;height:1px;opacity:0"></textarea></div></section>`;
}
function recoveryMarkup(profile) { if (!profile || profile.coverage === "none") return '<p>No target repair event occurred in this session.</p>'; if (profile.coverage === "limited") return `<p>Too few repair events for a stable recovery estimate.</p><dl><div><dt>Target errors observed</dt><dd>${profile.errorEpisodeCount}</dd></div><div><dt>Corrected</dt><dd>${profile.correctedEpisodeCount}</dd></div><div><dt>Extra correct characters deleted</dt><dd>${profile.correctCharactersRemoved}</dd></div></dl>`; return `<dl><div><dt>Target errors observed</dt><dd>${profile.errorEpisodeCount}</dd></div><div><dt>Corrected</dt><dd>${profile.correctedEpisodeCount}</dd></div><div><dt>Extra correct characters deleted</dt><dd>${profile.correctCharactersRemoved}</dd></div><div><dt>Typical repair time</dt><dd>${number(profile.errorToRepairMedianMs)} ms</dd></div><div><dt>Typical return-to-fluent time</dt><dd>${number(profile.resumeToFluentMedianMs)} ms</dd></div></dl>`; }
export function renderPracticeAccuracyRecoveryResult(root, finalResult) { const summary = finalResult?.summary ?? {}; const result = summary?.analysis ?? summary?.trainingQuality ?? {}; const before = summary?.beforeMetrics ?? result?.beforeMetrics ?? null; const after = summary?.afterMetrics ?? result?.afterMetrics ?? null; const recovery = result?.recoveryProfile ?? summary?.trainingQuality?.recoveryProfile ?? null; const target = result?.target ?? summary?.configuration?.target ?? {}; root.innerHTML = `<section class="screen practice-lab-screen practice-weak-key-results" data-practice-view="accuracy-recovery-result"><div class="practice-lab-shell"><main class="practice-lab-detail"><div class="eyebrow">Accuracy & Recovery complete · ${typeLabel(target.entityType)}</div><h1>${escapeHtml(target.entityKey ?? "Target")}</h1><section class="practice-lab-empty-state"><h2>Baseline → Check</h2><dl class="practice-weak-key-result-grid"><div><dt>First-pass accuracy</dt><dd>${percent(before?.firstPassAccuracy)} → ${percent(after?.firstPassAccuracy)}</dd></div><div><dt>Accuracy change</dt><dd>${signed(result?.accuracyDeltaPp, " pp")}</dd></div><div><dt>Context-adjusted timing</dt><dd>${number(before?.timing?.fluentResidualMedianMs)} ms → ${number(after?.timing?.fluentResidualMedianMs)} ms</dd></div><div><dt>Timing change</dt><dd>${signed(result?.residualDeltaMs, " ms")}</dd></div><div><dt>Hesitation</dt><dd>${percent(before?.timing?.disfluencyRate)} → ${percent(after?.timing?.disfluencyRate)}</dd></div><div><dt>Execution quality</dt><dd>${number(before?.quality)} → ${number(after?.quality)}</dd></div></dl><p>A negative timing delta means faster relative to expected context. Accuracy and timing are shown separately.</p></section><section class="practice-lab-empty-state"><h2>Recovery observations · ${escapeHtml(recovery?.coverage ?? "none")}</h2>${recoveryMarkup(recovery)}</section><section class="practice-lab-empty-state"><h2>Dose completed</h2><p>1.0 direct acquisition dose · ${summary?.configuration?.targetOpportunityBudget ?? result?.targetOpportunityCount ?? "—"} target opportunities.</p></section><div class="practice-lab-notice">This compares the beginning and end of this practice session. Recovery metrics are observational and only exist when relevant errors occurred. Durable learning, transfer, and retention require later evidence.</div><div class="practice-weak-key-result-actions"><button type="button" data-accuracy-recovery-session-action="repeat">PRACTICE AGAIN</button><button type="button" data-accuracy-recovery-session-action="finish">BACK TO ACCURACY & RECOVERY</button></div></main></div></section>`; }
function normalizedInput(type, value) { return { type, value, source: "browser-input", monotonicTimestampMs: Math.max(0, globalThis.performance?.now?.() ?? Date.now()), wallTimestampUtc: new Date().toISOString(), modifiers: { ctrl: false, meta: false, alt: false, shift: false } }; }

export async function mountPracticeAccuracyRecoverySession({ root, session, onExit = () => {}, onRepeat = () => {}, logger = null, dependencies = {} } = {}) {
  if (!session?.experiment || !session?.contentPlan || !session?.accuracyRecoveryPlan) throw new TypeError("Accuracy & Recovery session host requires a prepared session");
  const dataStore = dependencies.dataStore ?? createPracticeIndexedDbStore(); const repository = dependencies.repository ?? createPracticeRepository({ dataStore, manifestStore: dependencies.manifestStore ?? createPracticeManifestStore() }); const initialized = dependencies.initialized ?? await repository.initializePracticeStorage(); assertPracticeAccuracyRecoverySessionContext(session.accuracyRecoveryPlan, initialized.context);
  const engine = (dependencies.engineFactory ?? createPracticeSessionEngine)({ repository, sessionId: session.accuracyRecoveryPlan.sessionId, profileId: initialized.profile.profileId, contextId: initialized.context.contextId, logger }); let result = null; let closed = false; let unsubscribe = null; let latest = null; let feedback = null; let feedbackTimer = null;
  const focus = () => queueMicrotask(() => root.querySelector?.("[data-accuracy-recovery-input]")?.focus?.({ preventScroll: true }));
  const render = (snapshot) => { latest = snapshot; if (!closed && !result) { renderPracticeAccuracyRecoverySessionSnapshot(root, { contentPlan: session.contentPlan, snapshot, repairFeedback: feedback }); if (snapshot.lifecycleState === "active") focus(); } };
  const finish = async (repeat = false) => { if (closed) return; closed = true; if (feedbackTimer) clearTimeout(feedbackTimer); unsubscribe?.(); root.removeEventListener("beforeinput", beforeInput); root.removeEventListener("keydown", keyDown); root.removeEventListener("click", click); try { await engine.destroy(); } catch {} try { dataStore.close?.(); } catch {} (repeat ? onRepeat : onExit)(result); };
  const beforeInput = (event) => { if (closed || result || !event.target?.closest?.("[data-accuracy-recovery-input]")) return; event.preventDefault(); if (INSERT_TYPES.has(event.inputType) && typeof event.data === "string") for (const value of Array.from(event.data.normalize("NFC"))) engine.handleInput(normalizedInput(value === " " ? "space" : "character", value)); else if (event.inputType === "deleteContentBackward") engine.handleInput(normalizedInput("backspace", "")); else if (event.inputType === "deleteWordBackward") engine.handleInput(normalizedInput("word-delete", "")); event.target.value = ""; };
  const keyDown = (event) => { if (event.key === "Escape" && !closed && !result) { event.preventDefault(); const state = engine.getSnapshot().lifecycleState; void (state === "paused" ? engine.resume() : state === "active" ? engine.pause("manual") : Promise.resolve()); } };
  const click = (event) => { const button = event.target?.closest?.(ACTION_SELECTOR); if (!button) return; const action = button.dataset.accuracyRecoverySessionAction; if (action === "pause") void engine.pause("manual"); else if (action === "resume") void engine.resume(); else if (action === "abandon") void engine.abandon("manual-stop").then(() => finish(false)).catch(() => finish(false)); else if (action === "repeat") void finish(true); else if (action === "finish") void finish(false); };
  root.addEventListener("beforeinput", beforeInput); root.addEventListener("keydown", keyDown); root.addEventListener("click", click);
  await engine.prepare({ experiment: session.experiment, configuration: session.configuration, contentPlan: session.contentPlan });
  unsubscribe = engine.subscribe((snapshot, event) => { if (event === "repair-feedback") { feedback = session.experiment.getRepairFeedbackSnapshot?.() ?? null; render(snapshot); if (feedbackTimer) clearTimeout(feedbackTimer); if (feedback) feedbackTimer = setTimeout(() => { feedback = null; if (latest && !result && !closed) render(latest); }, feedback.displayDurationMs ?? 700); return; } if (event === "completed") { void engine.complete().then((value) => { result = value; renderPracticeAccuracyRecoveryResult(root, value); }).catch((error) => { logger?.warn?.("Accuracy & Recovery result failed", error); void finish(false); }); return; } render(snapshot); });
  render(await engine.start());
  return Object.freeze({ exit: () => finish(false), repeat: () => finish(true), getSnapshot: () => engine.getSnapshot() });
}
