export const PRACTICE_METRONOME_VERSION = 1;
export const PRACTICE_METRONOME_POLICY_VERSION = 1;
export const PRACTICE_METRONOME_SCHEDULE_VERSION = 1;
export const PRACTICE_METRONOME_PLAN_VERSION = 1;
export const PRACTICE_METRONOME_CUE_VERSION = 1;
export const PRACTICE_METRONOME_ANALYSIS_VERSION = 1;
export const PRACTICE_METRONOME_RESULT_VERSION = 1;
export const PRACTICE_METRONOME_TREATMENT_VERSION = 1;

export const PRACTICE_METRONOME_EXPERIMENT_ID = "metronome-typing";
export const PRACTICE_METRONOME_OUTCOME_DOMAIN = "metronome-cadence";
export const PRACTICE_METRONOME_DURATIONS_MS = Object.freeze([120_000, 300_000, 480_000]);
export const PRACTICE_METRONOME_DEFAULT_DURATION_MS = 300_000;

export const PRACTICE_METRONOME_MIN_BPM = 90;
export const PRACTICE_METRONOME_MAX_BPM = 180;
export const PRACTICE_METRONOME_TARGET_BPM = 120;
export const PRACTICE_METRONOME_MIN_CHARS_PER_BEAT = 1;
export const PRACTICE_METRONOME_MAX_CHARS_PER_BEAT = 16;
export const PRACTICE_METRONOME_COUNT_IN_BEATS = 4;
export const PRACTICE_METRONOME_CUE_MODES = Object.freeze(["audio", "visual"]);

export const PRACTICE_METRONOME_WINDOW_MS = 5_000;
export const PRACTICE_METRONOME_MIN_BLOCK_DURATION_RATIO = 0.75;
export const PRACTICE_METRONOME_MIN_CONDITION_OPPORTUNITIES = 20;
export const PRACTICE_METRONOME_MIN_SILENT_OPPORTUNITIES = 30;
export const PRACTICE_METRONOME_MIN_TIMING_TRANSITIONS = 10;

export const PRACTICE_METRONOME_PATTERN_PACE_THRESHOLD_PERCENT = 3;
export const PRACTICE_METRONOME_PATTERN_VARIATION_THRESHOLD_PERCENT = 2;
export const PRACTICE_METRONOME_PATTERN_ACCURACY_THRESHOLD_PP = 2;
export const PRACTICE_METRONOME_PATTERN_DISFLUENCY_THRESHOLD_PP = 5;
export const PRACTICE_METRONOME_PATTERN_CORRECTION_THRESHOLD_PP = 2;
export const PRACTICE_METRONOME_PATTERNS = Object.freeze([
  "pulse-associated-steadier",
  "pulse-associated-higher-cost",
  "little-observed-difference",
  "mixed",
  "insufficient",
]);

export const PRACTICE_METRONOME_DELAYED_MIN_MS = 24 * 60 * 60 * 1000;
export const PRACTICE_METRONOME_DELAYED_MAX_MS = 30 * 24 * 60 * 60 * 1000;
