import { PRACTICE_LIMITS, PRACTICE_RECORD_VERSIONS } from "./practiceConstants.js";
import { createPracticeCustomTextId } from "./practiceIds.js";
import { PRACTICE_CUSTOM_TEXT_ERROR_CODES, PRACTICE_CUSTOM_TEXT_PROJECTION_VERSION } from "./practiceCustomTextConstants.js";
import { hashPracticeCustomTextSha256, practiceCustomTextUtf8Bytes } from "./practiceCustomTextHash.js";
import { customTextError, inspectPracticeCustomTextSource, normalizePracticeCustomTextTitle, validatePracticeCustomTextRecord } from "./practiceCustomTextValidation.js";
const iso = (now) => new Date(typeof now === "function" ? now() : now).toISOString();
const rowBytes = (row) => Number.isInteger(row?.sourceByteLength) && row.sourceByteLength >= 0 ? row.sourceByteLength : practiceCustomTextUtf8Bytes(row?.sourceText ?? row?.text ?? "").byteLength;
async function canonicalRecord(raw, { now = Date.now } = {}) {
  if (!raw) return null; const source = inspectPracticeCustomTextSource(raw.sourceText ?? raw.text ?? ""); const dataLocale = String(raw.dataLocale ?? raw.language ?? "").trim(); if (!dataLocale) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.LOCALE_MISMATCH, "Saved Custom Text has no explicit locale"); const sourceHash = await hashPracticeCustomTextSha256(source.sourceText);
  const record = { customTextId: String(raw.customTextId ?? ""), profileId: String(raw.profileId ?? ""), recordVersion: PRACTICE_RECORD_VERSIONS.customText, revision: Number.isInteger(raw.revision) && raw.revision > 0 ? raw.revision : 1, title: normalizePracticeCustomTextTitle(raw.title), sourceText: source.sourceText, sourceHash, dataLocale, sourceByteLength: source.byteLength, sourceGraphemeCount: source.graphemeCount, typingProjectionVersion: PRACTICE_CUSTOM_TEXT_PROJECTION_VERSION, createdAt: Number.isFinite(Date.parse(raw.createdAt ?? "")) ? raw.createdAt : iso(now), updatedAt: Number.isFinite(Date.parse(raw.updatedAt ?? "")) ? raw.updatedAt : (Number.isFinite(Date.parse(raw.createdAt ?? "")) ? raw.createdAt : iso(now)), lastPractisedAt: Number.isFinite(Date.parse(raw.lastPractisedAt ?? raw.lastUsedAt ?? "")) ? (raw.lastPractisedAt ?? raw.lastUsedAt) : null };
  const validation = validatePracticeCustomTextRecord(record); if (!validation.valid) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.HASH_MISMATCH, "Saved Custom Text record is invalid", { errors: validation.errors }); return record;
}
async function buildRecord({ customTextId, profileId, revision, title, sourceText, dataLocale, createdAt, updatedAt, lastPractisedAt = null }) {
  const source = inspectPracticeCustomTextSource(sourceText); const normalizedTitle = normalizePracticeCustomTextTitle(title); if (normalizedTitle.length > PRACTICE_LIMITS.customTextTitleLength) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.TOO_LARGE, "Custom Text title is too long"); const locale = String(dataLocale ?? "").trim(); if (!locale) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.LOCALE_MISMATCH, "Custom Text requires an explicit locale");
  const record = { customTextId, profileId, recordVersion: PRACTICE_RECORD_VERSIONS.customText, revision, title: normalizedTitle, sourceText: source.sourceText, sourceHash: await hashPracticeCustomTextSha256(source.sourceText), dataLocale: locale, sourceByteLength: source.byteLength, sourceGraphemeCount: source.graphemeCount, typingProjectionVersion: PRACTICE_CUSTOM_TEXT_PROJECTION_VERSION, createdAt, updatedAt, lastPractisedAt };
  const validation = validatePracticeCustomTextRecord(record); if (!validation.valid) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.HASH_MISMATCH, "Custom Text record failed validation", { errors: validation.errors }); return Object.freeze(record);
}
export function createPracticeCustomTextRepository({ dataStore, now = Date.now } = {}) {
  if (!dataStore) throw new TypeError("Custom Text repository requires the canonical Practice data store");
  async function listCustomTexts(profileId) { if (!profileId) return []; const rows = await dataStore.query("customTexts", "profileId", profileId); const output = []; for (const raw of rows) { if (raw.profileId !== profileId) continue; try { const record = await canonicalRecord(raw, { now }); output.push(record); if (JSON.stringify(raw) !== JSON.stringify(record)) await dataStore.put("customTexts", record); } catch { } } return output.sort((a, b) => String(b.updatedAt).localeCompare(String(a.updatedAt)) || a.customTextId.localeCompare(b.customTextId)); }
  async function getCustomText(customTextId, { profileId } = {}) { const raw = await dataStore.get("customTexts", customTextId); if (!raw || (profileId && raw.profileId !== profileId)) return null; const record = await canonicalRecord(raw, { now }); if (profileId && record.profileId !== profileId) return null; if (JSON.stringify(raw) !== JSON.stringify(record)) await dataStore.put("customTexts", record); return record; }
  async function createCustomText({ profileId, title, sourceText, dataLocale }) { const timestamp = iso(now); const record = await buildRecord({ customTextId: createPracticeCustomTextId(), profileId, revision: 1, title, sourceText, dataLocale, createdAt: timestamp, updatedAt: timestamp }); return dataStore.runTransaction(["customTexts"], "readwrite", async (transaction) => { const rows = await transaction.query("customTexts", "profileId", profileId); if (rows.length >= PRACTICE_LIMITS.customTextCount) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.STORAGE_LIMIT, "Custom Text item limit reached"); const totalBytes = rows.reduce((sum, row) => sum + rowBytes(row), 0) + record.sourceByteLength; if (totalBytes > PRACTICE_LIMITS.customTextTotalBytes) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.STORAGE_LIMIT, "Custom Text profile storage limit reached", { totalBytes }); await transaction.put("customTexts", record); return record; }); }
  async function updateCustomText({ customTextId, profileId, expectedRevision, title, sourceText, dataLocale }) { return dataStore.runTransaction(["customTexts"], "readwrite", async (transaction) => { const raw = await transaction.get("customTexts", customTextId); if (!raw || raw.profileId !== profileId) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.NOT_FOUND, "Custom Text does not exist"); const current = await canonicalRecord(raw, { now }); if (!Number.isInteger(expectedRevision) || current.revision !== expectedRevision) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.CONFLICT, "Custom Text was changed in another tab", { expectedRevision, actualRevision: current.revision }); const updated = await buildRecord({ customTextId, profileId, revision: current.revision + 1, title: title ?? current.title, sourceText: sourceText ?? current.sourceText, dataLocale: dataLocale ?? current.dataLocale, createdAt: current.createdAt, updatedAt: iso(now), lastPractisedAt: current.lastPractisedAt }); const rows = await transaction.query("customTexts", "profileId", profileId); const otherBytes = rows.filter((row) => row.customTextId !== customTextId).reduce((sum, row) => sum + rowBytes(row), 0); if (otherBytes + updated.sourceByteLength > PRACTICE_LIMITS.customTextTotalBytes) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.STORAGE_LIMIT, "Custom Text profile storage limit reached"); await transaction.put("customTexts", updated); return updated; }); }
  async function deleteCustomText(customTextId, { profileId } = {}) { return dataStore.runTransaction(["customTexts"], "readwrite", async (transaction) => { const current = await transaction.get("customTexts", customTextId); if (!current || (profileId && current.profileId !== profileId)) return false; await transaction.delete("customTexts", customTextId); return true; }); }
  async function deleteAllCustomTexts(profileId) { return dataStore.runTransaction(["customTexts"], "readwrite", async (transaction) => { const rows = await transaction.query("customTexts", "profileId", profileId); for (const row of rows) if (row.profileId === profileId) await transaction.delete("customTexts", row.customTextId); return rows.filter((row) => row.profileId === profileId).length; }); }
  async function markCustomTextPractised({ customTextId, profileId, revision, sourceHash, completedAt }) { return dataStore.runTransaction(["customTexts"], "readwrite", async (transaction) => { const raw = await transaction.get("customTexts", customTextId); if (!raw || raw.profileId !== profileId) return false; const current = await canonicalRecord(raw, { now }); if (current.revision !== revision || current.sourceHash !== sourceHash) return false; if (current.lastPractisedAt === completedAt) return true; await transaction.put("customTexts", { ...current, lastPractisedAt: completedAt }); return true; }); }
  return Object.freeze({ listCustomTexts, getCustomText, createCustomText, updateCustomText, deleteCustomText, deleteAllCustomTexts, markCustomTextPractised });
}
export function createPracticeCustomTextRepositoryFacade(options = {}) { const custom = createPracticeCustomTextRepository(options); return Object.freeze({ ...custom, createPracticeCustomText: custom.createCustomText, updatePracticeCustomText: custom.updateCustomText, deletePracticeCustomText: custom.deleteCustomText }); }
