export const PRACTICE_CUSTOM_TEXT_EXPERIMENT_ID = "custom-text";
export const PRACTICE_CUSTOM_TEXT_VERSION = 1;
export const PRACTICE_CUSTOM_TEXT_POLICY_VERSION = 1;
export const PRACTICE_CUSTOM_TEXT_PROJECTION_VERSION = 1;
export const PRACTICE_CUSTOM_TEXT_RESULT_VERSION = 1;
export const PRACTICE_CUSTOM_TEXT_PLAN_VERSION = 1;

export const PRACTICE_CUSTOM_TEXT_DEFAULT_TITLE = "Untitled text";
export const PRACTICE_CUSTOM_TEXT_MIN_GRAPHEMES = 20;
export const PRACTICE_CUSTOM_TEXT_MAX_GRAPHEMES = 100_000;
export const PRACTICE_CUSTOM_TEXT_MAX_BYTES = 256 * 1024;
export const PRACTICE_CUSTOM_TEXT_MAX_ITEMS = 50;
export const PRACTICE_CUSTOM_TEXT_MAX_PROFILE_BYTES = 5 * 1024 * 1024;
export const PRACTICE_CUSTOM_TEXT_MAX_TITLE_LENGTH = 120;
export const PRACTICE_CUSTOM_TEXT_RENDER_WINDOW = 2_000;
export const PRACTICE_CUSTOM_TEXT_CHUNK_TARGET = 1_200;
export const PRACTICE_CUSTOM_TEXT_ENGINEERING_WPM = 400;
export const PRACTICE_CUSTOM_TEXT_CAPACITY_BUFFER = 1.10;
export const PRACTICE_CUSTOM_TEXT_TIMED_DURATIONS_MS = Object.freeze([1, 3, 5, 10, 15, 30].map((minutes) => minutes * 60_000));
export const PRACTICE_CUSTOM_TEXT_DEFAULT_TIMED_DURATION_MS = 5 * 60_000;
export const PRACTICE_CUSTOM_TEXT_SESSION_MODES = Object.freeze(["full-text", "selection", "timed"]);

export const PRACTICE_CUSTOM_TEXT_ERROR_CODES = Object.freeze({
  EMPTY: "CUSTOM_TEXT_EMPTY",
  TOO_SHORT: "CUSTOM_TEXT_TOO_SHORT",
  TOO_LARGE: "CUSTOM_TEXT_TOO_LARGE",
  STORAGE_LIMIT: "CUSTOM_TEXT_STORAGE_LIMIT",
  INVALID_CONTROL_CHARACTER: "CUSTOM_TEXT_INVALID_CONTROL_CHARACTER",
  UNSUPPORTED_GRAPHEME: "CUSTOM_TEXT_UNSUPPORTED_GRAPHEME",
  LOCALE_MISMATCH: "CUSTOM_TEXT_LOCALE_MISMATCH",
  INVALID_ENCODING: "CUSTOM_TEXT_INVALID_ENCODING",
  TIMED_CAPACITY: "CUSTOM_TEXT_TIMED_CAPACITY",
  NOT_FOUND: "CUSTOM_TEXT_NOT_FOUND",
  REVISION_MISMATCH: "CUSTOM_TEXT_REVISION_MISMATCH",
  CONFLICT: "CUSTOM_TEXT_CONFLICT",
  HASH_MISMATCH: "CUSTOM_TEXT_HASH_MISMATCH",
});

export function requiredPracticeCustomTextTimedGraphemes(durationMs) {
  const minutes = Number(durationMs) / 60_000;
  if (!Number.isFinite(minutes) || minutes <= 0) return Infinity;
  return Math.ceil(minutes * PRACTICE_CUSTOM_TEXT_ENGINEERING_WPM * 5 * PRACTICE_CUSTOM_TEXT_CAPACITY_BUFFER);
}
