import { createPracticeSessionPulse } from './practiceSessionPulse.js';
import { createPracticeSessionEngine } from './practiceSessionEngine.js';
import { createPracticeSessionId } from './practiceIds.js';
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function mountPracticeAssessmentSession({root,runtime,run,onExit=()=>{},engineFactory=createPracticeSessionEngine}={}) {
  let engine=null,unsubscribe=null,timer=null,closed=false,busy=false,prepared=null,preparedChars=[],completing=false;
  const disposeEngine=async()=>{timer?.stop();timer=null;unsubscribe?.();unsubscribe=null;await engine?.destroy();engine=null;};
  const focus=selector=>root.querySelector(selector)?.focus({preventScroll:true});
  const shell=body=>{root.innerHTML=`<section class="screen practice-lab-screen" data-practice-view="assessment-session"><div class="practice-lab-shell"><header class="practice-lab-header"><h1>Full Assessment</h1><button type="button" data-assessment-action="exit">END ASSESSMENT</button></header><main>${body}</main></div></section>`;};
  const between=()=>{const block=run.plan.blocks[run.progress.currentBlockIndex];shell(`<h2>${esc(block?.displayName??block?.blockId??'Assessment finished')}</h2><p>${run.blocks.filter(b=>b.status==='completed').length} of ${run.blocks.length} blocks completed.</p><p>Type naturally. Timing begins on your first key. Leaving a measurement ends that block.</p><button type="button" data-assessment-action="next">START NEXT BLOCK</button>`);focus('[data-assessment-action="next"]');};
  const fail=error=>{shell(`<h2>Assessment could not continue</h2><p role="alert">${esc(error.message)}</p><p>Your completed blocks remain saved.</p>`);focus('[data-assessment-action="exit"]');};
  const update=snapshot=>{const target=root.querySelector('[data-assessment-text]');if(!target)return;const cursor=snapshot.cursorIndex??0;const chars=preparedChars;const start=Math.max(0,cursor-100);if(target.dataset.cursor!==String(cursor)){target.dataset.cursor=String(cursor);target.innerHTML=chars.slice(start,cursor+400).map((c,i)=>`<span class="${i+start===cursor?'is-current':i+start<cursor?'is-typed':''}">${esc(c)}</span>`).join('');}root.querySelector('[data-assessment-time]').textContent=`${Math.ceil(Math.max(0,prepared.block.durationMs-(snapshot.timing?.activeDurationMs??0))/1000)} s remaining`;};
  const complete=async()=>{if(completing||closed)return;completing=true;try{await engine.complete();await disposeEngine();run=await runtime.repository.getAssessmentRun(run.assessmentRunId);if(run.blocks.every(b=>['completed','invalid'].includes(b.status))){run=(await runtime.service.finalizeAssessment(run.assessmentRunId)).run;shell(`<h2>Assessment complete</h2><p>${run.blocks.filter(b=>b.status==='completed').length} of ${run.blocks.length} blocks completed.</p><p>Results and coverage are saved locally. Open Skill Map and Progress to inspect your evidence.</p><button type="button" data-assessment-action="finish">VIEW RESULTS</button>`);focus('[data-assessment-action="finish"]');}else between();}catch(error){fail(error);}finally{completing=false;}};
  const next=async()=>{if(busy||engine||closed)return;busy=true;try{const sessionId=createPracticeSessionId();prepared=await runtime.service.prepareNextBlock({assessmentRunId:run.assessmentRunId,sessionId});if(closed)return;preparedChars=[...prepared.contentPlan.text];engine=engineFactory({repository:runtime.repository,sessionId,profileId:runtime.scope.profileId,contextId:runtime.scope.contextId});await engine.prepare({experiment:prepared.descriptor,configuration:prepared.configuration,contentPlan:prepared.contentPlan,evaluationPlan:prepared.evaluationPlan,evaluationArtifact:prepared.evaluationArtifact});if(closed){await disposeEngine();return;}shell(`<h2>${esc(prepared.block.displayName??prepared.block.blockId)}</h2><p data-assessment-time></p><div data-assessment-text class="practice-real-text-typing" role="region" aria-label="Assessment passage" style="white-space:pre-wrap"></div><label>Type the passage<textarea data-assessment-input autocomplete="off" autocapitalize="off" spellcheck="false" rows="2"></textarea></label>`);unsubscribe=engine.subscribe((snapshot,event)=>{if(event==='completed')void complete();else update(snapshot);});update(await engine.start());timer=createPracticeSessionPulse({run:()=>engine.tick(),intervalMs:100,isActive:()=>Boolean(engine)&&!completing&&!closed,onError:fail});timer.start();focus('[data-assessment-input]');}catch(error){await disposeEngine();fail(error);}finally{busy=false;}};
  const input=event=>{if(!event.target.closest?.('[data-assessment-input]')||!engine||closed)return;event.preventDefault();const send=(type,value)=>engine.handleInput({type,value,source:'browser-input',monotonicTimestampMs:performance.now(),wallTimestampUtc:new Date().toISOString(),modifiers:{ctrl:false,meta:false,alt:false,shift:false}});if(['insertText','insertCompositionText'].includes(event.inputType)&&event.data)for(const c of [...event.data.normalize('NFC')])send(c===' '?'space':'character',c);else if(event.inputType==='deleteContentBackward')send('backspace','');else if(event.inputType==='insertLineBreak')send('character','\n');event.target.value='';};
  const exit=async()=>{if(closed)return;closed=true;root.removeEventListener('click',click);root.removeEventListener('beforeinput',input);document.removeEventListener('visibilitychange',visibility);try{if(engine)await engine.abandon('manual-stop');await disposeEngine();if(run.status==='active')run=await runtime.service.abandonAssessment(run.assessmentRunId);}finally{onExit(run);}};
  const click=event=>{const action=event.target.closest?.('[data-assessment-action]')?.dataset.assessmentAction;if(!action)return;event.stopPropagation();if(action==='next')void next();else void exit();};
  const visibility=()=>{if(document.visibilityState==='hidden'&&engine)void exit();};
  root.addEventListener('click',click);root.addEventListener('beforeinput',input);document.addEventListener('visibilitychange',visibility);between();return {exit};
}
