import {
  PRACTICE_CONSISTENCY_ANALYSIS_WINDOW_MS,
  PRACTICE_CONSISTENCY_CALIBRATION_MS,
  PRACTICE_CONSISTENCY_DEFAULT_DURATION_MS,
  PRACTICE_CONSISTENCY_DURATIONS_MS,
  PRACTICE_CONSISTENCY_GUIDE_WINDOW_MS,
  PRACTICE_CONSISTENCY_POLICY_VERSION,
} from "./practiceConsistencyConstants.js";

export const PRACTICE_CONSISTENCY_POLICY_V1 = Object.freeze({
  version: PRACTICE_CONSISTENCY_POLICY_VERSION,
  durationsMs: PRACTICE_CONSISTENCY_DURATIONS_MS,
  defaultDurationMs: PRACTICE_CONSISTENCY_DEFAULT_DURATION_MS,
  calibrationDurationMs: PRACTICE_CONSISTENCY_CALIBRATION_MS,
  calibrationMinimumForwardInsertions: 50,
  calibrationMinimumFirstPassAccuracy: 0.70,
  guideWindowMs: PRACTICE_CONSISTENCY_GUIDE_WINDOW_MS,
  guideMinimumForwardInsertions: 20,
  guideLowerRatio: 0.90,
  guideUpperRatio: 1.10,
  guideAnnouncementCooldownMs: 10_000,
  analysisWindowMs: PRACTICE_CONSISTENCY_ANALYSIS_WINDOW_MS,
  structuralMinimumWindowMs: 25_000,
  structuralMinimumFirstPassOpportunities: 25,
  minimumValidWindows: 5,
  lowVariationMaximum: 0.05,
  highVariationMinimum: 0.08,
  smallDriftMaximum: 0.05,
  materialDriftMinimum: 0.075,
  controlStable: Object.freeze({ accuracyMADpp: 2, disfluencyMADpp: 5, correctionCostMADpp: 5 }),
  controlVariable: Object.freeze({ accuracyMADpp: 3, disfluencyMADpp: 7, correctionCostMADpp: 7 }),
  form: Object.freeze({
    minimumReadyForms: 4,
    targetFormCount: 6,
    minimumGraphemes: 22_000,
    maximumGraphemes: 30_000,
    minimumAvailableModelWeight: 0.90,
    minimumDifficultyPercentile: 20,
    maximumDifficultyPercentile: 80,
    slidingWindowGraphemes: 600,
    slidingWindowStrideGraphemes: 300,
    minimumWindowDifficultyPercentile: 15,
    maximumWindowDifficultyPercentile: 85,
    maximumWindowDifficultySpread: 0.50,
  }),
});
