import {
  PRACTICE_NUMBERS_SYMBOLS_DEFAULT_PRACTICE_DURATION_MS,
  PRACTICE_NUMBERS_SYMBOLS_POLICY_VERSION,
  PRACTICE_NUMBERS_SYMBOLS_PRACTICE_DURATIONS_MS,
} from "./practiceNumbersSymbolsConstants.js";

export const PRACTICE_NUMBERS_SYMBOLS_POLICY_V1 = Object.freeze({
  version: PRACTICE_NUMBERS_SYMBOLS_POLICY_VERSION,
  practiceDurationsMs: PRACTICE_NUMBERS_SYMBOLS_PRACTICE_DURATIONS_MS,
  defaultPracticeDurationMs: PRACTICE_NUMBERS_SYMBOLS_DEFAULT_PRACTICE_DURATION_MS,
  practiceMinimumReadyForms: 2,
  practiceTargetFormCount: 4,
  checkMinimumReadyForms: 4,
  checkTargetFormCount: 6,
  checkMinimumGraphemes: 1_800,
  checkMaximumGraphemes: 2_100,
  checkPrimaryOpportunityCount: 180,
  checkCategoryQuotas: Object.freeze({
    digit: 118,
    "operator-symbol": 22,
    "identifier-symbol": 18,
    "commerce-percent-symbol": 22,
  }),
  minimumDigitOccurrences: 8,
  maximumDigitOccurrences: 18,
  minimumSymbolOccurrences: 3,
  minimumOperatorOccurrences: 3,
  minimumIdentifierOccurrences: 4,
  minimumCommercePercentOccurrences: 4,
  minimumDigitRuns: 24,
  digitRunMinimumMix: Object.freeze({ 2: 8, 3: 8, 4: 4, "5-6": 4 }),
  minimumMixedPracticalTokens: 24,
  maximumExactMixedTokenRepeats: 2,
  regionCount: 8,
  minimumPrimaryPerRegion: 15,
  maximumDensityMedianMultiplier: 2,
  nonDigitCategoryMinimumRegions: 6,
  maximumLengthDeviationFromMedian: 0.05,
  maximumAlphabeticContextDeviationFromMedian: 0.10,
  minimumAvailableModelWeight: 0.90,
  practiceCapacityWpm: 400,
  practiceCapacityMargin: 0.10,
});
