export const PRACTICE_REAL_TEXT_VERSION = 1;
export const PRACTICE_REAL_TEXT_POLICY_VERSION = 1;
export const PRACTICE_REAL_TEXT_POOL_SCHEMA_VERSION = 1;
export const PRACTICE_REAL_TEXT_GENERATOR_VERSION = 1;
export const PRACTICE_REAL_TEXT_SELECTION_VERSION = 1;
export const PRACTICE_REAL_TEXT_RESULT_VERSION = 1;
export const PRACTICE_COLD_TRANSFER_LAUNCH_VERSION = 1;

export const PRACTICE_REAL_TEXT_EXPERIMENT_ID = "real-text";
export const PRACTICE_REAL_TEXT_EXPERIMENT_VERSION = 1;
export const PRACTICE_REAL_TEXT_COLD_TRANSFER_EXPERIMENT_ID = "real-text-cold-transfer";
export const PRACTICE_REAL_TEXT_COLD_TRANSFER_EXPERIMENT_VERSION = 1;

export const PRACTICE_REAL_TEXT_POOL_ID = "WS-REALTEXT-EN-1";
export const PRACTICE_REAL_TEXT_POOL_VERSION = 1;
export const PRACTICE_REAL_TEXT_POOL_STATUSES = Object.freeze(["draft", "review", "ready", "retired"]);

export const PRACTICE_REAL_TEXT_DURATIONS_MS = Object.freeze([180_000, 300_000, 600_000]);
export const PRACTICE_REAL_TEXT_DEFAULT_DURATION_MS = 300_000;
export const PRACTICE_COLD_TRANSFER_DURATION_MS = 60_000;
// The current Practice input contract accepts character graphemes and one canonical space input,
// not an Enter/newline action. Keep the broad-text bundle typable without special input handling.
export const PRACTICE_REAL_TEXT_SEPARATOR = " ";

export const PRACTICE_REAL_TEXT_ERRORS = Object.freeze({
  UNSUPPORTED_LANGUAGE: "REAL_TEXT_UNSUPPORTED_LANGUAGE",
  POOL_NOT_READY: "REAL_TEXT_POOL_NOT_READY",
  POOL_STALE: "REAL_TEXT_POOL_STALE",
  DURATION_UNSUPPORTED: "REAL_TEXT_DURATION_UNSUPPORTED",
  INSUFFICIENT_CAPACITY: "REAL_TEXT_INSUFFICIENT_CAPACITY",
  CONTENT_HASH_MISMATCH: "REAL_TEXT_CONTENT_HASH_MISMATCH",
  COLD_TRANSFER_UNAVAILABLE: "REAL_TEXT_COLD_TRANSFER_UNAVAILABLE",
  COLD_TRANSFER_HISTORY_PARTIAL: "REAL_TEXT_COLD_TRANSFER_HISTORY_PARTIAL",
  COLD_TRANSFER_EXHAUSTED: "REAL_TEXT_COLD_TRANSFER_EXHAUSTED",
});
