import { renderPracticeLabV28 } from "./practiceLabRendererV28.js";
import { PRACTICE_CONSISTENCY_DURATIONS_MS } from "./practiceConsistencyConstants.js";
import { PRACTICE_ENDURANCE_PRACTICE_DURATIONS_MS } from "./practiceEnduranceConstants.js";

const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[char]);
const minutes = (ms) => Math.round(ms / 60_000);
const durationButtons = (values, selected, action, enabledValues = values) => values.map((value) => `<button type="button" data-practice-action="${action}" data-duration-ms="${value}" aria-pressed="${selected === value ? "true" : "false"}" ${enabledValues.includes?.(value) ? "" : "disabled"}>${minutes(value)} min</button>`).join("");

export function renderPracticeConsistencyDetail(root, view, { focusSelector = null } = {}) {
  const available = view.availability?.available === true && !view.starting;
  root.innerHTML = `<section class="screen practice-lab-screen" data-practice-view="consistency-detail"><div class="practice-lab-shell"><header class="practice-lab-header"><button type="button" class="practice-lab-back" data-practice-action="back">← Back to Practice Lab</button><span class="practice-lab-status is-preview">DEVELOPER PREVIEW</span></header><main class="practice-lab-detail"><div class="eyebrow">Fluency · pace stability</div><h1>Consistency Trainer</h1><p class="practice-lab-lead">Practice steadier natural-text pacing with a gentle self-calibrated pace guide, while keeping short-term variation separate from longer drift.</p><section class="practice-lab-empty-state"><h2>Continuous natural text</h2><p>Type natural text at a comfortable pace. The first 30 seconds establishes your own reference. After calibration, a gentle guide says whether recent pace is slower, steady, or faster relative to that fixed reference.</p><fieldset><legend>Duration</legend><div class="practice-lab-duration-grid">${durationButtons(PRACTICE_CONSISTENCY_DURATIONS_MS, view.durationMs, "consistency-duration", view.availability?.supportedDurationsMs ?? [])}</div></fieldset><div class="practice-lab-notice" role="note">No target WPM, metronome, live numeric WPM, aggregate accuracy, PB, leaderboard, or 0–100 consistency score. Variation and directional drift are reported separately after the session.</div><button type="button" class="practice-lab-primary-action" data-practice-action="start-consistency" ${available ? "" : "disabled"}>${view.starting ? "STARTING…" : `START ${minutes(view.durationMs)}-MIN CONSISTENCY`}</button></section>${view.errorCode ? `<p role="alert">${escapeHtml(view.errorCode)}</p>` : ""}</main></div></section>`;
  (root.querySelector?.(focusSelector) ?? root.querySelector?.("[data-practice-action='start-consistency']") ?? root.querySelector?.("button"))?.focus?.({ preventScroll: true }); return true;
}

export function renderPracticeEnduranceDetail(root, view, { focusSelector = null } = {}) {
  const practiceAvailable = view.availability?.practiceAvailable === true && !view.starting; const checkAvailable = view.availability?.checkAvailable === true && !view.starting;
  root.innerHTML = `<section class="screen practice-lab-screen" data-practice-view="endurance-detail"><div class="practice-lab-shell"><header class="practice-lab-header"><button type="button" class="practice-lab-back" data-practice-action="back">← Back to Practice Lab</button><span class="practice-lab-status is-preview">DEVELOPER PREVIEW</span></header><main class="practice-lab-detail"><div class="eyebrow">Fluency · sustained performance</div><h1>Endurance</h1><p class="practice-lab-lead">Practice sustained natural-text typing for 5–20 minutes, or run a standardized 10-minute Endurance Check to measure how late-session performance compares with an earlier settled period.</p><section class="practice-lab-empty-state"><h2>Endurance Practice</h2><p>Repeatable long-form training with continuous target-blind natural prose. Practice is descriptive and does not update PL13 endurance ability.</p><fieldset><legend>Practice duration</legend><div class="practice-lab-duration-grid">${durationButtons(PRACTICE_ENDURANCE_PRACTICE_DURATIONS_MS, view.durationMs, "endurance-duration", view.availability?.practiceDurationsMs ?? [])}</div></fieldset><button type="button" class="practice-lab-primary-action" data-practice-action="start-endurance-practice" ${practiceAvailable ? "" : "disabled"}>${view.starting === "practice" ? "STARTING…" : `START ${minutes(view.durationMs)}-MIN PRACTICE`}</button></section><section class="practice-lab-empty-state"><div class="eyebrow">Standardized · 10 minutes</div><h2>Endurance Check</h2><p>A fixed diagnostic protocol: 60 seconds to settle in, followed by 18 measured 30-second windows. Endurance ability is based on robust adjusted first-pass effective pace during the final three measured minutes.</p><div class="practice-lab-notice" role="note">No live WPM, accuracy graph, decline warning, or pace correction. One valid completed Check can produce exactly one PL13 endurance observation. Observed decline is not labeled as fatigue.</div><button type="button" class="practice-lab-primary-action" data-practice-action="start-endurance-check" ${checkAvailable ? "" : "disabled"}>${view.starting === "check" ? "STARTING…" : "START 10-MIN ENDURANCE CHECK"}</button></section>${view.errorCode ? `<p role="alert">${escapeHtml(view.errorCode)}</p>` : ""}</main></div></section>`;
  (root.querySelector?.(focusSelector) ?? root.querySelector?.("[data-practice-action='start-endurance-practice']") ?? root.querySelector?.("button"))?.focus?.({ preventScroll: true }); return true;
}

export function renderPracticeLabV29(root, view, options = {}) {
  if (view?.kind === "consistency-detail") return renderPracticeConsistencyDetail(root, view, options);
  if (view?.kind === "endurance-detail") return renderPracticeEnduranceDetail(root, view, options);
  return renderPracticeLabV28(root, view, options);
}
