export const PRACTICE_SUSTAINED_WINDOW_VERSION = 1;
export const PRACTICE_SUSTAINED_FORM_GENERATOR_VERSION = 1;
export const PRACTICE_SUSTAINED_WINDOW_DURATION_MS = 30_000;
export const PRACTICE_SUSTAINED_MAX_WINDOWS = 40;
