import {
  PRACTICE_ENDURANCE_CHECK_DURATION_MS,
  PRACTICE_ENDURANCE_CHECK_SETTLING_MS,
  PRACTICE_ENDURANCE_DEFAULT_PRACTICE_DURATION_MS,
  PRACTICE_ENDURANCE_POLICY_VERSION,
  PRACTICE_ENDURANCE_PRACTICE_DURATIONS_MS,
  PRACTICE_ENDURANCE_WINDOW_MS,
} from "./practiceEnduranceConstants.js";

export const PRACTICE_ENDURANCE_POLICY_V1 = Object.freeze({
  version: PRACTICE_ENDURANCE_POLICY_VERSION,
  practiceDurationsMs: PRACTICE_ENDURANCE_PRACTICE_DURATIONS_MS,
  defaultPracticeDurationMs: PRACTICE_ENDURANCE_DEFAULT_PRACTICE_DURATION_MS,
  checkDurationMs: PRACTICE_ENDURANCE_CHECK_DURATION_MS,
  checkSettlingMs: PRACTICE_ENDURANCE_CHECK_SETTLING_MS,
  fiveMinutePracticeSettlingMs: 30_000,
  longPracticeSettlingMs: 60_000,
  windowMs: PRACTICE_ENDURANCE_WINDOW_MS,
  structuralMinimumWindowMs: 25_000,
  structuralMinimumFirstPassOpportunities: 25,
  checkEarlyWindowOrdinals: Object.freeze([1, 2, 3, 4]),
  checkLateWindowOrdinals: Object.freeze([15, 16, 17, 18]),
  checkAbilityWindowOrdinals: Object.freeze([13, 14, 15, 16, 17, 18]),
  minimumEarlyLateValidWindows: 3,
  minimumAbilityValidWindows: 5,
  minimumAbilityPooledFirstPassAccuracy: 0.70,
  paceDeclineRetentionMaximumPercent: 92,
  stableRetentionMinimumPercent: 95,
  risingRetentionMinimumPercent: 105,
  controlDegradation: Object.freeze({ accuracyDeltaPp: -3, disfluencyDeltaPp: 7, correctionCostDeltaPp: 7 }),
  controlPreserved: Object.freeze({ accuracyDeltaPp: -2, disfluencyDeltaPp: 5, correctionCostDeltaPp: 5 }),
  uncertainty: Object.freeze({ effectiveSampleCount: 4, spreadFloorLog: 0.02, protocolPenaltyLog: 0.03, sigmaFloorLog: 0.05, sigmaCeilingLog: 0.20 }),
  form: Object.freeze({
    minimumAvailableModelWeight: 0.90,
    minimumDifficultyPercentile: 20,
    maximumDifficultyPercentile: 80,
    maximumDigitRatio: 0.02,
    maximumSymbolRatio: 0.01,
    slidingWindowGraphemes: 800,
    slidingWindowStrideGraphemes: 400,
    checkMinimumReadyForms: 4,
    checkTargetFormCount: 6,
    checkMinimumGraphemes: 22_000,
    checkMaximumGraphemes: 30_000,
    checkMaximumWindowDifficultySpread: 0.40,
    practiceMinimumReadyForms: 2,
    practiceTargetFormCount: 4,
    practiceMinimumGraphemes: 44_000,
    practicePreferredMinimumGraphemes: 48_000,
    practiceMaximumGraphemes: 60_000,
    practiceMaximumWindowDifficultySpread: 0.55,
  }),
});
