import { createPracticeLabController as createPracticeLabControllerV22 } from "./practiceLabControllerRuntimeV22.js";
import { renderPracticeLabV22 } from "./practiceLabRendererV22.js";
import { renderPracticeAccuracyRecoveryDetail } from "./practiceLabRendererV23.js";
import { buildPracticeAccuracyRecoveryDetailViewModel, createDefaultPracticeAccuracyRecoveryUiState, normalizePracticeAccuracyRecoveryManualInput, normalizePracticeAccuracyRecoveryUiState } from "./practiceAccuracyRecoveryUi.js";
import { registerPracticeAccuracyRecoveryExperiment } from "./practiceAccuracyRecoveryExperiment.js";
import { PRACTICE_LAB_ROUTES } from "./practiceLabRoutes.js";

const ID = "accuracy-control";
const REC_STATUSES = new Set(["ready", "no-evidence", "unsupported", "unavailable"]);
const typeToManual = (type) => type === "key" ? "key" : type === "word" ? "word" : "combination";

export function createPracticeLabController(options = {}) {
  const { root, experimentRegistry, logger = null, accuracyRecoveryRecommendationLoader = null, accuracyRecoveryWarningsLoader = null } = options;
  registerPracticeAccuracyRecoveryExperiment(experimentRegistry);
  let state = createDefaultPracticeAccuracyRecoveryUiState(); let sessionHost = null; let mounted = false; let lastView = null; let inspectEpoch = 0; let prepareEpoch = 0; let recommendationEpoch = 0; let listeners = false; const externalRenderer = typeof options.renderer === "function" ? options.renderer : null;
  function isDetail(view) { return view?.kind === "experiment-detail" && view?.title === "Accuracy & Recovery"; }
  function attach() { if (!listeners && mounted) { root?.addEventListener?.("click", click, true); root?.addEventListener?.("input", input, true); listeners = true; } }
  function detach() { if (listeners) { root?.removeEventListener?.("click", click, true); root?.removeEventListener?.("input", input, true); listeners = false; } }
  function renderer(renderRoot, view, rendererOptions = {}) { lastView = view; if (isDetail(view)) { attach(); const detail = buildPracticeAccuracyRecoveryDetailViewModel({ entry: view, resolved: { runnable: view.runnable }, state }); return externalRenderer ? externalRenderer(renderRoot, detail, rendererOptions) : renderPracticeAccuracyRecoveryDetail(renderRoot, detail, rendererOptions); } detach(); return externalRenderer ? externalRenderer(renderRoot, view, rendererOptions) : renderPracticeLabV22(renderRoot, view, rendererOptions); }
  const base = createPracticeLabControllerV22({ ...options, renderer });
  const isRoute = () => base.getSnapshot()?.route?.name === PRACTICE_LAB_ROUTES.EXPERIMENT_DETAIL && base.getSnapshot()?.route?.params?.experimentId === ID;
  const rerender = (focusSelector = null) => { if (mounted && !sessionHost && isRoute() && lastView) renderer(root, lastView, { focusSelector }); };
  const setState = (patch, focusSelector = null) => { state = normalizePracticeAccuracyRecoveryUiState({ ...state, ...patch }); rerender(focusSelector); };
  const loadRecommendations = async () => {
    if (!mounted || !isRoute() || state.recommendationStatus !== "idle") return false; const epoch = ++recommendationEpoch; setState({ recommendationStatus: "loading" });
    try { const result = typeof accuracyRecoveryRecommendationLoader === "function" ? await accuracyRecoveryRecommendationLoader() : await import("./practiceAccuracyRecoveryRecommendationRuntime.js").then((module) => module.loadPracticeAccuracyRecoveryRecommendations()); if (!mounted || epoch !== recommendationEpoch || !isRoute()) return false; const status = REC_STATUSES.has(result?.status) ? result.status : "unavailable"; setState({ recommendationStatus: status, recommendations: status === "ready" ? result.recommendations ?? [] : [], recommendationErrorCode: status === "unavailable" ? result?.errorCode ?? "RECOMMENDATIONS_UNAVAILABLE" : null }); return status === "ready"; }
    catch (error) { if (epoch === recommendationEpoch) setState({ recommendationStatus: "unavailable", recommendations: [], recommendationErrorCode: error?.code ?? "RECOMMENDATIONS_UNAVAILABLE" }); return false; }
  };
  const warningsFor = async (target) => { const recommended = state.recommendations.find((item) => item.entityType === target.entityType && item.entityKey === target.entityKey); const warnings = []; if (recommended?.hierarchyDeemphasized) warnings.push({ kind: "hierarchy", message: "Some of this target's difficulty may be explained by a lower-level limiter." }); if (recommended?.saturationDeemphasized) warnings.push({ kind: "saturation", message: "Recent similar acquisition practice appears to have low marginal gain." }); if (warnings.length) return warnings; try { const result = typeof accuracyRecoveryWarningsLoader === "function" ? await accuracyRecoveryWarningsLoader(target) : await import("./practiceAccuracyRecoveryRecommendationRuntime.js").then((module) => module.loadPracticeAccuracyRecoveryManualWarnings(target)); return result?.warnings ?? []; } catch { return []; } };
  const inspect = async ({ value, manualType = state.manualType, targetSource = "manual", explicitEntityType = null } = {}) => {
    const normalized = explicitEntityType ? { valid: true, normalizedValue: value, target: { entityType: explicitEntityType, entityKey: value }, reasonCode: null, message: null } : normalizePracticeAccuracyRecoveryManualInput(value, manualType, "en"); const epoch = ++inspectEpoch;
    if (!normalized.valid) { setState({ manualType, targetValue: normalized.normalizedValue, entityType: null, selectedSource: targetSource, status: "unsupported", reasonCode: normalized.reasonCode, message: normalized.message, warnings: [], availability: null }, "[data-accuracy-recovery-target]"); return false; }
    setState({ manualType: typeToManual(normalized.target.entityType), targetValue: normalized.target.entityKey, entityType: normalized.target.entityType, selectedSource: targetSource, status: "checking", reasonCode: null, message: null, warnings: [] });
    const registration = experimentRegistry.getRegistration(ID);
    try { const [availability, warnings] = await Promise.all([registration?.runtime?.inspectTarget?.({ entityType: normalized.target.entityType, entityKey: normalized.target.entityKey, manualType: typeToManual(normalized.target.entityType) }), warningsFor(normalized.target)]); if (!mounted || epoch !== inspectEpoch || !isRoute()) return false; const status = ["ready", "limited-content", "unsupported", "unavailable"].includes(availability?.status) ? availability.status : "unavailable"; setState({ status, reasonCode: availability?.reasons?.[0] ?? null, availability, warnings }); return status === "ready"; }
    catch (error) { if (epoch === inspectEpoch) setState({ status: "unavailable", reasonCode: error?.code ?? "TRAINING_CORPUS_NOT_READY", availability: null }); return false; }
  };
  const prepare = async () => {
    const normalized = normalizePracticeAccuracyRecoveryManualInput(state.targetValue, state.manualType, "en"); if (!normalized.valid && !state.entityType) return false; const target = state.entityType ? { entityType: state.entityType, entityKey: state.targetValue } : normalized.target; const epoch = ++prepareEpoch; setState({ status: "preparing" }); const registration = experimentRegistry.getRegistration(ID);
    try { const prepared = await registration.setupFactory({ entityType: target.entityType, entityKey: target.entityKey, manualType: typeToManual(target.entityType), targetSource: state.selectedSource }); if (!mounted || epoch !== prepareEpoch) return false; const session = registration.sessionFactory(prepared); const { mountPracticeAccuracyRecoverySession } = await import("./practiceAccuracyRecoverySessionHost.js"); detach(); sessionHost = await mountPracticeAccuracyRecoverySession({ root, session, logger, onExit() { sessionHost = null; if (mounted) setState({ status: "ready" }, "[data-accuracy-recovery-target]"); }, onRepeat() { sessionHost = null; if (mounted) void prepare(); } }); return true; }
    catch (error) { if (mounted && epoch === prepareEpoch) { logger?.warn?.("Accuracy & Recovery preparation failed", error); setState({ status: "unavailable", reasonCode: error?.code ?? "TRAINING_CORPUS_NOT_READY" }); } return false; }
  };
  function click(event) { const button = event.target?.closest?.("[data-practice-action]"); if (!button || !root?.contains?.(button)) return; const action = button.dataset.practiceAction; if (action === "set-accuracy-recovery-type") { event.stopPropagation(); setState({ manualType: button.dataset.manualType, entityType: button.dataset.manualType === "key" ? "key" : button.dataset.manualType === "word" ? "word" : null, targetValue: "", status: "idle", warnings: [] }, "[data-accuracy-recovery-target]"); } else if (action === "choose-accuracy-recovery-target") { event.stopPropagation(); void inspect({ value: button.dataset.entityKey, manualType: typeToManual(button.dataset.entityType), explicitEntityType: button.dataset.entityType, targetSource: "recommended" }); } else if (action === "start-accuracy-recovery") { event.stopPropagation(); void prepare(); } }
  function input(event) { const target = event.target?.closest?.("[data-accuracy-recovery-target]"); if (target && root?.contains?.(target)) void inspect({ value: target.value, manualType: state.manualType, targetSource: "manual" }); }
  const afterRoute = () => { if (isRoute() && state.recommendationStatus === "idle") void loadRecommendations(); };
  return Object.freeze({ mount(route) { mounted = true; const result = base.mount(route); queueMicrotask(afterRoute); return result; }, navigate(...args) { const result = base.navigate(...args); queueMicrotask(afterRoute); return result; }, back() { if (sessionHost) { void sessionHost.exit(); return true; } const result = base.back(); queueMicrotask(afterRoute); return result; }, getSnapshot() { const snapshot = base.getSnapshot(); return Object.freeze({ ...snapshot, accuracyRecovery: Object.freeze({ status: state.status, manualType: state.manualType, entityType: state.entityType, targetValue: state.targetValue, recommendationStatus: state.recommendationStatus, recommendationCount: state.recommendations.length, sessionActive: Boolean(sessionHost) }) }); }, subscribe(listener) { return base.subscribe(listener); }, unmount() { mounted = false; inspectEpoch += 1; prepareEpoch += 1; recommendationEpoch += 1; detach(); if (sessionHost) { void sessionHost.exit(); sessionHost = null; } return base.unmount(); } });
}
