const freezeDeep=(v)=>{if(!v||typeof v!=="object"||Object.isFrozen(v))return v;Object.values(v).forEach(freezeDeep);return Object.freeze(v);};
function blockAt(blocks,ms){let lo=0,hi=blocks.length-1;while(lo<=hi){const m=(lo+hi)>>1,b=blocks[m];if(ms<b.startMs)hi=m-1;else if(ms>=b.endMs)lo=m+1;else return b;}return null;}
function mergeInterval(list,start,end){if(!(end>start))return;let s=start,e=end,i=0;while(i<list.length&&list[i][1]<s)i++;while(i<list.length&&list[i][0]<=e){s=Math.min(s,list[i][0]);e=Math.max(e,list[i][1]);list.splice(i,1);}list.splice(i,0,[s,e]);}
export function createPracticeReadAheadBlockAccumulator({plan}={}){
 if(!plan?.blocks?.length)throw new TypeError("Read-Ahead accumulator requires plan");
 const states=new Map(plan.blocks.map(b=>[b.blockId,{block:{...b},acceptedForwardInsertions:0,firstPassOpportunityCount:0,correctFirstPassAttempts:0,eligibleTimingCount:0,disfluentTimingCount:0,correctionIntervals:[],visibilityInterrupted:false,contentExhausted:false,protocolCorrupt:false}]));
 function current(ms){const b=blockAt(plan.blocks,Number(ms));return b?states.get(b.blockId):null;}
 function recordProcessedInput(event={}){const s=current(event.activeSessionMs);if(!s)return false;if(event.type==="character"&&event.acceptedForward===true)s.acceptedForwardInsertions+=1;if(event.isFirstAttempt===true){s.firstPassOpportunityCount+=1;if(event.correctness==="correct"||event.firstPassCorrect===true)s.correctFirstPassAttempts+=1;}if(["fluent","disfluent"].includes(event.latencyClass)&&Number.isFinite(event.previousActiveSessionMs)){const prior=current(event.previousActiveSessionMs);if(prior?.block.blockId===s.block.blockId){s.eligibleTimingCount+=1;if(event.latencyClass==="disfluent")s.disfluentTimingCount+=1;}}return true;}
 function recordClosedErrorEpisode(episode={}){const start=Number(episode.startActiveSessionMs??episode.startedAtActiveMs);const end=Number(episode.endActiveSessionMs??episode.closedAtActiveMs);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return false;const a=current(start),b=current(Math.max(start,end-0.0001));if(!a||!b||a.block.blockId!==b.block.blockId)return false;mergeInterval(a.correctionIntervals,start,end);return true;}
 function mark(kind,ms){const s=current(ms);if(!s)return false;if(kind==="visibility")s.visibilityInterrupted=true;else if(kind==="content")s.contentExhausted=true;else s.protocolCorrupt=true;return true;}
 function finalize(activeDurationMs=plan.durationMs){const total=Math.max(0,Math.min(plan.durationMs,Number(activeDurationMs)||0));const blocks=plan.blocks.map(b=>{const s=states.get(b.blockId);const observedDurationMs=Math.max(0,Math.min(total,b.endMs)-b.startMs);const correctionCostMs=s.correctionIntervals.reduce((sum,[a,z])=>sum+(z-a),0);return freezeDeep({...s.block,observedDurationMs,acceptedForwardInsertions:s.acceptedForwardInsertions,firstPassOpportunityCount:s.firstPassOpportunityCount,correctFirstPassAttempts:s.correctFirstPassAttempts,eligibleTimingCount:s.eligibleTimingCount,disfluentTimingCount:s.disfluentTimingCount,correctionCostMs,visibilityInterrupted:s.visibilityInterrupted,contentExhausted:s.contentExhausted,protocolCorrupt:s.protocolCorrupt});});return freezeDeep({blocks});}
 return Object.freeze({recordProcessedInput,recordClosedErrorEpisode,markVisibilityInterruption:(ms)=>mark("visibility",ms),markContentExhausted:(ms)=>mark("content",ms),markProtocolCorrupt:(ms)=>mark("protocol",ms),finalize});
}
