import { createPracticeContentPlan } from "./practiceSessionContract.js";
import { splitGraphemes } from "./practiceTextSegmentation.js";
import { PRACTICE_CUSTOM_TEXT_ERROR_CODES, PRACTICE_CUSTOM_TEXT_PLAN_VERSION, PRACTICE_CUSTOM_TEXT_POLICY_VERSION, PRACTICE_CUSTOM_TEXT_PROJECTION_VERSION, PRACTICE_CUSTOM_TEXT_SESSION_MODES, PRACTICE_CUSTOM_TEXT_TIMED_DURATIONS_MS, PRACTICE_CUSTOM_TEXT_VERSION, requiredPracticeCustomTextTimedGraphemes } from "./practiceCustomTextConstants.js";
import { hashPracticeCustomTextSha256 } from "./practiceCustomTextHash.js";
import { assertPracticeCustomTextSessionable, buildPracticeCustomTypingProjection } from "./practiceCustomTextProjection.js";
import { customTextError, inspectPracticeCustomTextSource } from "./practiceCustomTextValidation.js";
const freezeDeep = (value) => { if (!value || typeof value !== "object" || Object.isFrozen(value)) return value; Object.values(value).forEach(freezeDeep); return Object.freeze(value); };
function clampSelection(sourceText, selectionRange) { if (!selectionRange || !Number.isInteger(selectionRange.start) || !Number.isInteger(selectionRange.end) || selectionRange.start < 0 || selectionRange.end <= selectionRange.start || selectionRange.end > sourceText.length) return null; return { start: selectionRange.start, end: selectionRange.end }; }
export async function buildPracticeCustomTextPlan({ sessionId, profileId, contextId, dataLocale, sourceText, sourceKind = "ephemeral", customTextId = null, revision = null, sourceHash: boundSourceHash = null, sessionMode = "full-text", timedDurationMs = null, selectionRange = null } = {}) {
  if (!sessionId || !profileId || !contextId || !dataLocale) throw new TypeError("Custom Text plan requires Practice identity and locale"); if (!PRACTICE_CUSTOM_TEXT_SESSION_MODES.includes(sessionMode)) throw new TypeError("Unsupported Custom Text session mode"); if (!["saved", "ephemeral"].includes(sourceKind)) throw new TypeError("Unsupported Custom Text source kind"); if (sourceKind === "saved" && (!customTextId || !Number.isInteger(revision))) throw new TypeError("Saved Custom Text plan requires document identity"); if (sourceKind === "ephemeral" && customTextId != null) throw new TypeError("Ephemeral Custom Text cannot carry a saved document ID");
  const source = inspectPracticeCustomTextSource(sourceText); const sourceHash = await hashPracticeCustomTextSha256(source.sourceText); if (boundSourceHash && boundSourceHash !== sourceHash) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.HASH_MISMATCH, "Custom Text changed before session start");
  let projectedSource = source.sourceText; let selectedRange = null; if (sessionMode === "selection") { selectedRange = clampSelection(source.sourceText, selectionRange); if (!selectedRange) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.TOO_SHORT, "Choose a meaningful text selection before starting"); projectedSource = source.sourceText.slice(selectedRange.start, selectedRange.end); }
  const projection = assertPracticeCustomTextSessionable(buildPracticeCustomTypingProjection(projectedSource)); if (sessionMode === "timed") { if (!PRACTICE_CUSTOM_TEXT_TIMED_DURATIONS_MS.includes(timedDurationMs)) throw new TypeError("Unsupported Custom Text timed duration"); const required = requiredPracticeCustomTextTimedGraphemes(timedDurationMs); if (projection.graphemeCount < required) throw customTextError(PRACTICE_CUSTOM_TEXT_ERROR_CODES.TIMED_CAPACITY, "Custom Text is too short for this timed duration without repeating it", { requiredGraphemes: required, availableGraphemes: projection.graphemeCount }); }
  const typingHash = await hashPracticeCustomTextSha256(`${PRACTICE_CUSTOM_TEXT_PROJECTION_VERSION}\n${projection.text}`); const serializedSelectionRange = selectedRange ? { start: selectedRange.start, end: selectedRange.end } : null; const planBinding = JSON.stringify({ version: PRACTICE_CUSTOM_TEXT_PLAN_VERSION, projectionVersion: PRACTICE_CUSTOM_TEXT_PROJECTION_VERSION, sourceKind, customTextId, revision: sourceKind === "saved" ? revision : null, sourceHash, typingHash, sessionMode, timedDurationMs: sessionMode === "timed" ? timedDurationMs : null, selectionRange: serializedSelectionRange, typingGraphemeCount: projection.graphemeCount }); const planHash = await hashPracticeCustomTextSha256(planBinding);
  const contentPlan = createPracticeContentPlan({ contentId: `practice-content_custom-text-${sessionId.replace(/[^a-z0-9._-]/gi, "-")}`, contentGeneratorVersion: PRACTICE_CUSTOM_TEXT_PROJECTION_VERSION, text: projection.text, targetEntities: [], completion: sessionMode === "timed" ? { mode: "duration", value: timedDurationMs } : { mode: "content", value: null }, metadata: { partition: null, corpusPartition: null, corpusContentId: null, sourceType: "user-local", contentPurpose: "custom", evidenceRole: "custom", customText: { version: PRACTICE_CUSTOM_TEXT_VERSION, policyVersion: PRACTICE_CUSTOM_TEXT_POLICY_VERSION, projectionVersion: PRACTICE_CUSTOM_TEXT_PROJECTION_VERSION, sourceKind, customTextId: sourceKind === "saved" ? customTextId : null, revision: sourceKind === "saved" ? revision : null, sourceHash, typingHash, sessionMode, timedDurationMs: sessionMode === "timed" ? timedDurationMs : null, selectionRange: serializedSelectionRange, planHash, resumable: false } } });
  return freezeDeep({ version: PRACTICE_CUSTOM_TEXT_PLAN_VERSION, sessionId, profileId, contextId, dataLocale, sourceKind, customTextId: sourceKind === "saved" ? customTextId : null, revision: sourceKind === "saved" ? revision : null, sourceHash, typingHash, sourceGraphemeCount: source.graphemeCount, typingGraphemeCount: projection.graphemeCount, projectionVersion: PRACTICE_CUSTOM_TEXT_PROJECTION_VERSION, sessionMode, timedDurationMs: sessionMode === "timed" ? timedDurationMs : null, selectionRange: serializedSelectionRange, planHash, contentPlan });
}
export function getPracticeCustomTextRenderWindow(text, cursorIndex, { windowSize = 2_000 } = {}) { const graphemes = splitGraphemes(text); const cursor = Math.max(0, Math.min(graphemes.length, Number(cursorIndex) || 0)); const before = Math.floor(windowSize * 0.3); const start = Math.max(0, Math.min(cursor - before, Math.max(0, graphemes.length - windowSize))); const end = Math.min(graphemes.length, start + windowSize); return Object.freeze({ start, end, graphemes: graphemes.slice(start, end), total: graphemes.length }); }
