import {
  PRACTICE_PUNCTUATION_CAPITALS_DEFAULT_PRACTICE_DURATION_MS,
  PRACTICE_PUNCTUATION_CAPITALS_POLICY_VERSION,
  PRACTICE_PUNCTUATION_CAPITALS_PRACTICE_DURATIONS_MS,
} from "./practicePunctuationCapitalsConstants.js";

export const PRACTICE_PUNCTUATION_CAPITALS_POLICY_V1 = Object.freeze({
  version: PRACTICE_PUNCTUATION_CAPITALS_POLICY_VERSION,
  practiceDurationsMs: PRACTICE_PUNCTUATION_CAPITALS_PRACTICE_DURATIONS_MS,
  defaultPracticeDurationMs: PRACTICE_PUNCTUATION_CAPITALS_DEFAULT_PRACTICE_DURATION_MS,
  practiceMinimumReadyForms: 2,
  practiceTargetFormCount: 4,
  checkMinimumReadyForms: 4,
  checkTargetFormCount: 6,
  checkMinimumGraphemes: 1_800,
  checkMaximumGraphemes: 2_100,
  checkPrimaryOpportunityCount: 180,
  checkCategoryQuotas: Object.freeze({
    "capital-letter": 54,
    comma: 32,
    "terminal-mark": 32,
    "colon-semicolon": 14,
    "quote-apostrophe": 26,
    "bracket-dash": 22,
  }),
  minimumSentenceCapitals: 32,
  minimumBoundaryOpportunities: 60,
  regionCount: 8,
  minimumPrimaryPerRegion: 15,
  maximumDensityMedianMultiplier: 2,
  majorCategoryMinimumRegions: 6,
  minorCategoryMinimumRegions: 4,
  maximumLengthDeviationFromMedian: 0.05,
  maximumWordCountDeviationFromMedian: 0.07,
  maximumMeanWordLengthSpread: 0.30,
  minimumAvailableModelWeight: 0.90,
  maximumFeatureRmsFromCentroid: 0.65,
  maximumDifficultyIndexSpread: 0.45,
  practiceCapacityWpm: 400,
  practiceCapacityMargin: 0.10,
});
