import { renderPracticeLabV22 } from "./practiceLabRendererV22.js";

const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]);
const typeLabel = (type) => ({ key: "Key", bigram: "Bigram", trigram: "Trigram", word: "Word" })[type] ?? "Target";
function recommendations(view) {
  if (view.recommendationStatus === "loading") return '<p class="practice-lab-muted">Loading evidence-based targets…</p>';
  if (!view.recommendations.length) return '<p class="practice-lab-muted">No accuracy or recovery limiter is currently well-established. Manual selection remains available.</p>';
  return `<div class="practice-combination-recommendations">${view.recommendations.map((item) => `<button type="button" data-practice-action="choose-accuracy-recovery-target" data-entity-type="${escapeHtml(item.entityType)}" data-entity-key="${escapeHtml(item.entityKey)}"><strong>${escapeHtml(item.entityKey)}</strong><span>${escapeHtml(typeLabel(item.entityType))} · ${escapeHtml(item.limiterPhenotype ?? "Mixed")}</span><small>${Math.round(item.evidenceConfidenceScore ?? 0)}% evidence confidence${item.hierarchyDeemphasized ? " · lower-level explanation present" : ""}${item.saturationDeemphasized ? " · recent similar practice may have low marginal gain" : ""}</small></button>`).join("")}</div>`;
}
function notice(view) {
  if (view.status === "checking" || view.status === "preparing") return `<div class="practice-lab-notice" role="status"><strong>${view.status === "preparing" ? "Building fixed intervention…" : "Checking approved training content…"}</strong></div>`;
  if (["limited-content", "unsupported", "unavailable"].includes(view.status)) return `<div class="practice-lab-notice" role="alert"><strong>Target unavailable</strong><p>${escapeHtml(view.message ?? view.reasonCode ?? "The full v1 protocol cannot be built for this target.")}</p></div>`;
  return "";
}
function warnings(view) { return view.warnings.length ? `<div class="practice-lab-notice" role="note">${view.warnings.map((warning) => `<p>${escapeHtml(warning.message)}</p>`).join("")}</div>` : ""; }
function phases(view) { return `<ol class="practice-combination-plan">${view.phases.map((phase) => `<li><span class="practice-combination-plan-index">${phase.ordinal}</span><div><strong>${escapeHtml(phase.label)}</strong><p>${phase.id === "baseline" ? "Uncued pre-practice target observation" : phase.id === "control" ? "Manageable target-rich contexts; subtle cue" : phase.id === "repair" ? "Broader contexts; natural errors repaired normally" : phase.id === "mix" ? "Target-bearing + target-free material; no cue" : "Matched same-session check; no cue"}</p></div><span>${phase.opportunityQuota ?? "—"}</span></li>`).join("")}</ol>`; }

export function renderPracticeAccuracyRecoveryDetail(root, view, { focusSelector = null } = {}) {
  root.innerHTML = `<section class="screen practice-lab-screen" data-practice-view="accuracy-recovery-detail"><div class="practice-lab-shell"><header class="practice-lab-header"><button type="button" class="practice-lab-back" data-practice-action="back">← Back to Practice Lab</button><span class="practice-lab-status is-preview">DEVELOPER PREVIEW</span></header><main class="practice-lab-detail"><div class="eyebrow">Precision · control intervention</div><h1>Accuracy & Recovery</h1><p class="practice-lab-lead">Practice clean first-pass typing and more precise recovery when errors occur, without chasing an artificially slow perfect score.</p>
    <section class="practice-lab-empty-state"><h2>Recommended targets</h2>${recommendations(view)}</section>
    <section class="practice-lab-empty-state"><h2>Manual target</h2><p>Choose the entity family explicitly. The same text may represent different skills—for example, <code>the</code> can be a trigram or a word.</p><div class="practice-combination-type-toggle" role="group" aria-label="Target type"><button type="button" data-practice-action="set-accuracy-recovery-type" data-manual-type="key" aria-pressed="${view.manualType === "key"}">KEY</button><button type="button" data-practice-action="set-accuracy-recovery-type" data-manual-type="combination" aria-pressed="${view.manualType === "combination"}">COMBINATION</button><button type="button" data-practice-action="set-accuracy-recovery-type" data-manual-type="word" aria-pressed="${view.manualType === "word"}">WORD</button></div><label class="practice-combination-target-field"><span>Target</span><input data-accuracy-recovery-target type="text" value="${escapeHtml(view.targetValue)}" maxlength="24" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false"></label>${warnings(view)}${notice(view)}<button type="button" class="practice-lab-primary-action" data-practice-action="start-accuracy-recovery" ${view.canStart ? "" : "disabled"}>START ACCURACY & RECOVERY</button></section>
    <section class="practice-lab-empty-state"><h2>What this mode trains</h2><p>Aim for clean first-pass typing at a comfortable normal pace. If an error happens, repair it precisely and return to your rhythm.</p><p>No errors are injected, no 98% rule is imposed, and forward typing is never blocked until correction.</p></section>
    <section class="practice-lab-empty-state"><h2>Session structure${view.targetOpportunityBudget ? ` · ${view.targetOpportunityBudget} target opportunities` : ""}</h2>${phases(view)}<p>Recovery evidence is opportunistic. An error-free session can show strong first-pass control while recovery remains unobserved.</p></section>
  </main></div></section>`;
  (root.querySelector?.(focusSelector) ?? root.querySelector?.("[data-accuracy-recovery-target]") ?? root.querySelector?.("button"))?.focus?.({ preventScroll: true });
  return true;
}
export function renderPracticeLabV23(root, view, options = {}) { if (view?.kind === "accuracy-recovery-detail") return renderPracticeAccuracyRecoveryDetail(root, view, options); return renderPracticeLabV22(root, view, options); }
