export const PRACTICE_READ_AHEAD_VERSION = 1;
export const PRACTICE_READ_AHEAD_POLICY_VERSION = 1;
export const PRACTICE_READ_AHEAD_FORM_SCHEMA_VERSION = 1;
export const PRACTICE_READ_AHEAD_FORM_GENERATOR_VERSION = 1;
export const PRACTICE_READ_AHEAD_VISIBILITY_VERSION = 1;
export const PRACTICE_READ_AHEAD_SCHEDULE_VERSION = 1;
export const PRACTICE_READ_AHEAD_ANALYSIS_VERSION = 1;
export const PRACTICE_READ_AHEAD_RESULT_VERSION = 1;
export const PRACTICE_READ_AHEAD_SELECTION_VERSION = 1;

export const PRACTICE_READ_AHEAD_EXPERIMENT_ID = "read-ahead";
export const PRACTICE_READ_AHEAD_FORM_SET_ID = "WS-READAHEAD-EN-1";
export const PRACTICE_READ_AHEAD_FORM_SET_VERSION = 1;
export const PRACTICE_READ_AHEAD_TARGET_FORM_COUNT = 6;
export const PRACTICE_READ_AHEAD_MINIMUM_READY_FORMS = 4;

export const PRACTICE_READ_AHEAD_DURATIONS_MS = Object.freeze([180_000, 360_000, 600_000]);
export const PRACTICE_READ_AHEAD_DEFAULT_DURATION_MS = 360_000;
export const PRACTICE_READ_AHEAD_BASELINE_MS = 30_000;
export const PRACTICE_READ_AHEAD_INTEGRATION_MS = 30_000;
export const PRACTICE_READ_AHEAD_VISIBLE_FUTURE_WORDS = Object.freeze([1, 2, 4]);
export const PRACTICE_READ_AHEAD_MASTER_SCHEDULE = Object.freeze([1, 2, 4, 2, 1, 4, 2, 4, 1, 4, 2, 1, 4, 1, 2, 1, 4, 2]);

export const PRACTICE_READ_AHEAD_FORM_MIN_GRAPHEMES = 22_000;
export const PRACTICE_READ_AHEAD_FORM_PREFERRED_GRAPHEMES = Object.freeze([24_000, 30_000]);
export const PRACTICE_READ_AHEAD_TYPABILITY_WINDOW_GRAPHEMES = 600;
export const PRACTICE_READ_AHEAD_TYPABILITY_WINDOW_STRIDE = 300;
export const PRACTICE_READ_AHEAD_MIN_MODEL_WEIGHT = 0.90;
export const PRACTICE_READ_AHEAD_MAX_DIFFICULTY_SPREAD = 0.45;
export const PRACTICE_READ_AHEAD_MAX_DIGIT_RATIO = 0.01;
export const PRACTICE_READ_AHEAD_MAX_SYMBOL_RATIO = 0.005;

export const PRACTICE_READ_AHEAD_MIN_TIMING_TRANSITIONS = 10;
export const PRACTICE_READ_AHEAD_MIN_BLOCK_OPPORTUNITIES = 25;
export const PRACTICE_READ_AHEAD_MIN_BASELINE_OPPORTUNITIES = 40;
export const PRACTICE_READ_AHEAD_PL32_MIN_BASELINE_OPPORTUNITIES = 50;
export const PRACTICE_READ_AHEAD_PL32_MIN_BASELINE_ACCURACY = 0.70;
export const PRACTICE_READ_AHEAD_MIN_BLOCK_DURATION_RATIO = 0.75;

export const PRACTICE_READ_AHEAD_PATTERN_PACE_THRESHOLD_PERCENT = 3;
export const PRACTICE_READ_AHEAD_PATTERN_ACCURACY_THRESHOLD_PP = 2;
export const PRACTICE_READ_AHEAD_PATTERN_DISFLUENCY_THRESHOLD_PP = 5;
export const PRACTICE_READ_AHEAD_PATTERNS = Object.freeze([
  "more-preview-associated",
  "less-preview-associated",
  "little-observed-difference",
  "mixed",
  "insufficient",
]);

export const PRACTICE_READ_AHEAD_PL32_MIN_DELAY_MS = 24 * 60 * 60 * 1000;
export const PRACTICE_READ_AHEAD_PL32_MAX_DELAY_MS = 30 * 24 * 60 * 60 * 1000;
export const PRACTICE_READ_AHEAD_PL32_PRACTICAL_THRESHOLD_PERCENT = 3;
