import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { access, mkdir, readFile, readdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PRACTICE_CORPUS_PARTITIONS } from "../js/practiceLab/practiceCorpusConstants.js";
import {
  PRACTICE_TEXT_FEATURE_VERSION,
} from "../js/practiceLab/practiceTextDifficultyFeatures.js";
import {
  PRACTICE_TYPABILITY_COVERAGE_THRESHOLDS_V1,
  PRACTICE_TYPABILITY_MODEL_KIND,
  PRACTICE_TYPABILITY_MODEL_VERSION,
  PRACTICE_TYPABILITY_PERCENTILE_METHOD,
  PRACTICE_TYPABILITY_REFERENCE_VERSION,
  PRACTICE_TYPABILITY_WEIGHTS_V1,
  validatePracticeTypabilityReference,
} from "../js/practiceLab/practiceTypabilityModel.js";
import { buildPracticeTypabilityArtifacts } from "./lib/practiceTypabilityBuildCore.mjs";

const root = fileURLToPath(new URL("../", import.meta.url));
const practiceRoot = path.join(root, "data", "practice");
const modelsRoot = path.join(practiceRoot, "models");
const runtimeFile = path.join(root, "js", "practiceLab", "generated", "practiceTypabilityRuntimeData.js");
const validateOnly = process.argv.includes("--validate");
const unknownArgs = process.argv.slice(2).filter((arg) => arg !== "--validate");
if (unknownArgs.length) throw new Error(`Unknown Practice typability build argument: ${unknownArgs[0]}`);

const hashBytes = (value) => `sha256-${createHash("sha256").update(value).digest("hex")}`;
const jsonText = (value) => `${JSON.stringify(value, null, 2)}\n`;

async function exists(file) {
  try { await access(file); return true; } catch { return false; }
}

async function readJson(file) {
  return JSON.parse(await readFile(file, "utf8"));
}

function runtimeModuleText(build) {
  const byHash = {};
  for (const [partition, rows] of Object.entries(build.scores)) {
    for (const row of rows) byHash[row.sessionContentHash] = {
      ...row,
      partition,
    };
  }
  const payload = {
    en: {
      reference: build.reference,
      staticScoresBySessionContentHash: byHash,
    },
  };
  return `// Generated by scripts/buildPracticeTypability.mjs. Do not edit by hand.\nconst freezeDeep = (value) => {\n  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;\n  Object.values(value).forEach(freezeDeep);\n  return Object.freeze(value);\n};\n\nexport const PRACTICE_TYPABILITY_RUNTIME_ARTIFACTS = freezeDeep(${JSON.stringify(payload, null, 2)});\n`;
}

function createOutput(build, corpusManifest, indexManifest) {
  const referenceText = jsonText(build.reference);
  const scoreTexts = Object.fromEntries(Object.entries(build.scores).map(([partition, rows]) => [partition, jsonText({
    artifactVersion: 1,
    modelVersion: PRACTICE_TYPABILITY_MODEL_VERSION,
    featureVersion: PRACTICE_TEXT_FEATURE_VERSION,
    referenceVersion: PRACTICE_TYPABILITY_REFERENCE_VERSION,
    corpusId: corpusManifest.corpusId,
    corpusVersion: corpusManifest.corpusVersion,
    corpusChecksum: corpusManifest.buildChecksum,
    indexChecksum: indexManifest.indexChecksum,
    partition,
    items: rows,
  })]));
  const runtimeText = runtimeModuleText(build);
  const artifactChecksums = [
    { path: "typability-v1.reference.json", text: referenceText },
    ...Object.entries(scoreTexts).map(([partition, text]) => ({ path: `${partition}.json`, text })),
    { path: "js/practiceLab/generated/practiceTypabilityRuntimeData.js", text: runtimeText, external: true },
  ].map(({ path: artifactPath, text, external = false }) => ({
    path: artifactPath,
    sha256: hashBytes(Buffer.from(text, "utf8")),
    bytes: Buffer.byteLength(text, "utf8"),
    external,
  }));
  const frequency = build.frequencyMetadata;
  const manifest = {
    manifestVersion: 1,
    modelVersion: PRACTICE_TYPABILITY_MODEL_VERSION,
    featureVersion: PRACTICE_TEXT_FEATURE_VERSION,
    referenceVersion: PRACTICE_TYPABILITY_REFERENCE_VERSION,
    modelKind: PRACTICE_TYPABILITY_MODEL_KIND,
    percentileMethod: PRACTICE_TYPABILITY_PERCENTILE_METHOD,
    language: corpusManifest.language,
    corpusId: corpusManifest.corpusId,
    corpusVersion: corpusManifest.corpusVersion,
    corpusChecksum: corpusManifest.buildChecksum,
    indexSchemaVersion: indexManifest.indexSchemaVersion,
    indexChecksum: indexManifest.indexChecksum,
    segmentationVersion: indexManifest.segmentationVersion,
    tokenizationVersion: indexManifest.tokenizationVersion,
    frequencyReferenceVersion: frequency.referenceVersion,
    frequencyReferenceChecksum: frequency.checksum,
    frequencySourceIds: frequency.sourceIds,
    frequencyReferenceId: frequency.referenceId,
    weights: { ...PRACTICE_TYPABILITY_WEIGHTS_V1 },
    coverageThresholds: { ...PRACTICE_TYPABILITY_COVERAGE_THRESHOLDS_V1 },
    referencePartition: "training",
    referenceItemCount: build.reference.referenceItemCount,
    fitPartitions: build.diagnostics.fitPartitions,
    protectedFitExclusions: build.diagnostics.protectedFitExclusions,
    scoredPartitions: Object.keys(build.scores),
    researchHoldoutScored: false,
    referenceChecksum: hashBytes(Buffer.from(referenceText, "utf8")),
    artifactChecksums,
  };
  return {
    manifestText: jsonText(manifest),
    referenceText,
    scoreTexts,
    runtimeText,
    manifest,
  };
}

function validateManifest(manifest, reference) {
  const errors = [];
  if (manifest.manifestVersion !== 1) errors.push("manifestVersion");
  if (manifest.modelVersion !== PRACTICE_TYPABILITY_MODEL_VERSION) errors.push("modelVersion");
  if (manifest.featureVersion !== PRACTICE_TEXT_FEATURE_VERSION) errors.push("featureVersion");
  if (manifest.referenceVersion !== PRACTICE_TYPABILITY_REFERENCE_VERSION) errors.push("referenceVersion");
  if (manifest.referencePartition !== "training") errors.push("referencePartition");
  if (manifest.fitPartitions.length !== 1 || manifest.fitPartitions[0] !== "training") errors.push("fitPartitions");
  for (const partition of ["transfer", "benchmark", "diagnostic", "research-holdout"]) if (!manifest.protectedFitExclusions.includes(partition)) errors.push(`protected:${partition}`);
  if (manifest.researchHoldoutScored !== false) errors.push("researchHoldoutScored");
  if (manifest.indexChecksum !== reference.indexChecksum || manifest.corpusChecksum !== reference.corpusChecksum) errors.push("binding");
  if (errors.length) throw new Error(`Practice typability model manifest is invalid: ${errors.join(", ")}`);
}

async function listFiles(directory) {
  if (!(await exists(directory))) return [];
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (entry.isDirectory()) files.push(...(await listFiles(path.join(directory, entry.name))).map((child) => `${entry.name}/${child}`));
    else if (entry.isFile()) files.push(entry.name);
  }
  return files;
}

async function validateCheckedIn(modelDir, output) {
  const expected = new Map([
    ["manifest.json", output.manifestText],
    ["typability-v1.reference.json", output.referenceText],
    ...Object.entries(output.scoreTexts).map(([partition, text]) => [`${partition}.json`, text]),
  ]);
  const actualPaths = await listFiles(modelDir);
  if (JSON.stringify(actualPaths) !== JSON.stringify([...expected.keys()].sort())) throw new Error("Practice typability artifact set is stale");
  for (const [relative, expectedText] of expected) {
    const actual = await readFile(path.join(modelDir, relative), "utf8");
    if (actual !== expectedText) throw new Error(`Practice typability artifact is stale: ${relative}`);
  }
  if (!(await exists(runtimeFile)) || await readFile(runtimeFile, "utf8") !== output.runtimeText) throw new Error("Practice typability runtime artifact is stale");
}

async function replaceSafely(modelDir, output) {
  const tempDir = `${modelDir}.tmp-${process.pid}`;
  const backupDir = `${modelDir}.bak-${process.pid}`;
  const runtimeTemp = `${runtimeFile}.tmp-${process.pid}`;
  const runtimeBackup = `${runtimeFile}.bak-${process.pid}`;
  await rm(tempDir, { recursive: true, force: true });
  await rm(backupDir, { recursive: true, force: true });
  await rm(runtimeTemp, { force: true });
  await rm(runtimeBackup, { force: true });
  const hadModel = await exists(modelDir);
  const hadRuntime = await exists(runtimeFile);
  try {
    await mkdir(tempDir, { recursive: true });
    await writeFile(path.join(tempDir, "manifest.json"), output.manifestText, "utf8");
    await writeFile(path.join(tempDir, "typability-v1.reference.json"), output.referenceText, "utf8");
    for (const [partition, text] of Object.entries(output.scoreTexts)) await writeFile(path.join(tempDir, `${partition}.json`), text, "utf8");
    await mkdir(path.dirname(runtimeFile), { recursive: true });
    await writeFile(runtimeTemp, output.runtimeText, "utf8");
    if (hadModel) await rename(modelDir, backupDir);
    if (hadRuntime) await rename(runtimeFile, runtimeBackup);
    try {
      await rename(tempDir, modelDir);
      await rename(runtimeTemp, runtimeFile);
      await rm(backupDir, { recursive: true, force: true });
      await rm(runtimeBackup, { force: true });
    } catch (cause) {
      await rm(modelDir, { recursive: true, force: true });
      await rm(runtimeFile, { force: true });
      if (hadModel && await exists(backupDir)) await rename(backupDir, modelDir);
      if (hadRuntime && await exists(runtimeBackup)) await rename(runtimeBackup, runtimeFile);
      throw cause;
    }
  } finally {
    await rm(tempDir, { recursive: true, force: true });
    await rm(backupDir, { recursive: true, force: true });
    await rm(runtimeTemp, { force: true });
    await rm(runtimeBackup, { force: true });
  }
}

// PL6/PL7 remain authoritative and must validate before PL10 derives any static model artifact.
execFileSync(process.execPath, [path.join(root, "scripts", "buildPracticeCorpus.mjs"), "--validate"], { stdio: "ignore" });
execFileSync(process.execPath, [path.join(root, "scripts", "buildPracticeIndexes.mjs"), "--validate"], { stdio: "ignore" });

const corpusManifest = await readJson(path.join(practiceRoot, "manifests", "en-v1.manifest.json"));
const indexManifest = await readJson(path.join(practiceRoot, "indexes", "en-v1", "manifest.json"));
const sourceRegistry = await readJson(path.join(practiceRoot, "provenance", "sources.json"));
const partitionArtifacts = {};
for (const partition of PRACTICE_CORPUS_PARTITIONS) partitionArtifacts[partition] = await readJson(path.join(practiceRoot, partition, "en-v1.json"));

// Optional frequency references are separate governed artifacts. None exists in the current PL6 provenance release.
const frequencyPath = path.join(practiceRoot, "provenance", "frequency", "en-v1.frequency.json");
const frequencyReference = await exists(frequencyPath) ? await readJson(frequencyPath) : null;
const build = buildPracticeTypabilityArtifacts({ corpusManifest, indexManifest, partitionArtifacts, sourceRegistry, frequencyReference });
const referenceValidation = validatePracticeTypabilityReference(build.reference);
if (!referenceValidation.valid) throw new Error(`Practice typability reference failed validation: ${JSON.stringify(referenceValidation.errors)}`);
const output = createOutput(build, corpusManifest, indexManifest);
validateManifest(output.manifest, build.reference);
const modelDir = path.join(modelsRoot, "en-v1");
if (validateOnly) await validateCheckedIn(modelDir, output);
else await replaceSafely(modelDir, output);

console.log(`Practice typability ${validateOnly ? "validated" : "built"}: ${corpusManifest.corpusId} v${corpusManifest.corpusVersion}`);
console.log(`  model=${PRACTICE_TYPABILITY_MODEL_VERSION} feature=${PRACTICE_TEXT_FEATURE_VERSION} reference=${PRACTICE_TYPABILITY_REFERENCE_VERSION}`);
console.log(`  fit=training(${build.reference.referenceItemCount}) scored=${build.diagnostics.scoredItemCount} holdoutScored=false`);
console.log(`  corpusChecksum=${corpusManifest.buildChecksum}`);
console.log(`  indexChecksum=${indexManifest.indexChecksum}`);
console.log(`  frequencyReference=${build.frequencyMetadata.referenceVersion ?? "none"}`);
